(() => {
  const page=new URL(location.href),id=page.searchParams.get('id'),supported=['a1-sounds','a1-numbers','a1-conversations','a1-basics','a1-life'];if(!supported.includes(id))return;
  const C=(id,skill,type,kind,prompt,correct,why,extra={})=>({id,skill,type,kind,prompt,correct,why,...extra});
  const configs={
    'a1-sounds':{labels:{patterns:'Sound patterns',spelling:'Spelling',listening:'Listening'},activities:[
      C('ei-sound','patterns','choice','See the pattern','Which spelling usually sounds like English “eye”?','ei','ei sounds like “eye,” as in mein.',{options:['ie','ei','eu']}),
      C('umlaut-fallback','spelling','input','Type the fallback','Write ü when an umlaut keyboard is unavailable.','ue','German convention writes ü as ue.',{answers:['ue']}),
      C('listen-schön','listening','listen','Hear the umlaut','Which word did Vivian say?','schön','ö distinguishes schön from schon.',{audio:'schön',options:['schon','schön','Sohn']}),
      C('dictate-strasse','spelling','dictation','Listen and spell','Type the word Vivian says.','Straße','Straße uses initial Str- and ß.',{audio:'Straße',answers:['straße','strasse']}),
      C('ie-sound','patterns','choice','Contrast the pattern','Which spelling normally sounds like a long “ee”?','ie','ie is a long ee, as in Liebe.',{options:['ei','ie','eu']}),
      C('build-patterns','patterns','tokens','Build what you hear','Build: My friend plays today.','Mein Freund spielt heute.','The sentence contains ei, eu, sp, and eu sound patterns.',{tokens:['Mein Freund','spielt','heute.'],answer:['Mein Freund','spielt','heute.']}),
      C('listen-deutsch','listening','listen','Sound to word','Which word did Vivian say?','Deutsch','eu sounds like “oy.”',{audio:'Deutsch',options:['Deutsch','deutlich','dich']}),
      C('sharp-s','spelling','input','Recall the spelling','Complete: Grü__e','ß','Grüße uses ß after the long ü sound.',{answers:['ß','ss']})]},
    'a1-numbers':{labels:{numbers:'Numbers',time:'Time',dates:'Dates & prices'},activities:[
      C('twenty-four','numbers','input','Produce the number','Write 24 in German.','vierundzwanzig','German says four-and-twenty.',{answers:['vierundzwanzig']}),
      C('thirty-five','numbers','choice','Decode the order','What number is fünfunddreißig?','35','fünf-und-dreißig is five-and-thirty.',{options:['53','35','305']}),
      C('half-nine','time','choice','Read everyday time','What time is halb neun?','8:30','It is halfway toward nine.',{options:['9:30','8:30','8:09']}),
      C('build-time','time','tokens','Build the time','Build: It is quarter past eight.','Es ist Viertel nach acht.','Viertel nach means quarter past.',{tokens:['Es ist','Viertel nach','acht.'],answer:['Es ist','Viertel nach','acht.']}),
      C('listen-price','dates','listen','Catch the price','Which price did Vivian say?','18,40 €','Listen for achtzehn Euro vierzig.',{audio:'Das macht achtzehn Euro vierzig.',options:['18,40 €','80,40 €','18,14 €']}),
      C('may-third','dates','input','Produce the date','Complete: am ___ Mai (on May third)','dritten','After am, the ordinal uses -en.',{answers:['dritten']}),
      C('schedule','time','listen','Catch schedule time','When does the train leave?','16:12','The announcement says sechzehn Uhr zwölf.',{audio:'Der Zug fährt um sechzehn Uhr zwölf.',options:['16:12','6:20','17:16']}),
      C('ninety-nine','numbers','input','Transfer the pattern','Write 99 in German.','neunundneunzig','German says nine-and-ninety.',{answers:['neunundneunzig']})]},
    'a1-conversations':{labels:{register:'Formal & informal',politeness:'Polite phrases',imperative:'Instructions'},activities:[
      C('formal-name','register','choice','Choose the register','Which question is formal?','Wie heißen Sie?','Formal address uses Sie.',{options:['Wie heißt du?','Wie heißen Sie?','Wie heißt ihr?']}),
      C('introduction','register','input','Complete the introduction','Complete: Ich ___ Lina.','heiße','Ich heiße … introduces your name.',{answers:['heiße','heisse']}),
      C('polite-order','politeness','tokens','Build a polite order','Build: I would like a coffee.','Ich hätte gern einen Kaffee.','hätte gern is a natural polite request.',{tokens:['Ich','hätte gern','einen Kaffee.'],answer:['Ich','hätte gern','einen Kaffee.']}),
      C('listen-shop','politeness','listen','Hear the shop question','What did the seller ask?','Anything else?','Sonst noch etwas? means Anything else?',{audio:'Sonst noch etwas?',options:['Anything else?','How much is it?','Would you like coffee?']}),
      C('formal-wait','imperative','choice','Use the formal command','Formal “Wait!”','Warten Sie!','Formal imperative uses infinitive + Sie.',{options:['Warte!','Warten Sie!','Wartet du!']}),
      C('du-command','imperative','input','Produce the command','Informal singular: ___ bitte rein!','Komm','The du imperative of kommen is Komm!',{answers:['komm']}),
      C('listen-closing','politeness','listen','Recognize the closing','Which meaning matches what Vivian says?','No thanks, that is all.','This closes a purchase politely.',{audio:'Nein, danke. Das ist alles.',options:['No thanks, that is all.','Yes, one more thing.','Please repeat that.']}),
      C('nice-meet','register','choice','Close the introduction','What naturally means “Nice to meet you”?','Freut mich!','Freut mich is the natural short response.',{options:['Freut mich!','Gute Reise!','Keine Ursache!']})]},
    'a1-basics':{labels:{negation:'Negation',possessives:'Possessives',connectors:'Connectors'},activities:[
      C('keinen-hund','negation','input','Negate the noun','Complete: Ich habe ___ Hund.','keinen','Masculine accusative uses keinen.',{answers:['keinen']}),
      C('nicht-expensive','negation','tokens','Negate a quality','Build: That is not expensive.','Das ist nicht teuer.','nicht negates the adjective teuer.',{tokens:['Das','ist','nicht','teuer.'],answer:['Das','ist','nicht','teuer.']}),
      C('meine-sister','possessives','choice','Choose the possessive','Das ist ___ Schwester.','meine','Feminine nominative adds -e.',{options:['mein','meine','meinen']}),
      C('meinen-brother','possessives','input','Add the ending','Ich sehe ___ Bruder.','meinen','Masculine accusative adds -en.',{answers:['meinen']}),
      C('reason-denn','connectors','choice','Choose the relationship','Which connector gives a reason and keeps main-clause order?','denn','denn means because without moving the verb.',{options:['aber','denn','oder']}),
      C('listen-contrast','connectors','listen','Hear the relationship','Which sentence did Vivian say?','Es ist klein, aber schön.','aber marks a contrast.',{audio:'Es ist klein, aber schön.',options:['Es ist klein, aber schön.','Es ist klein oder schön.','Es ist klein denn schön.']}),
      C('kein-auto','negation','choice','Choose kein or nicht','Ich habe ___ Auto.','kein','Auto could take ein, so use kein.',{options:['nicht','keinen','kein']}),
      C('build-reason','connectors','tokens','Build a reason','Build: I am leaving because I am tired.','Ich gehe, denn ich bin müde.','denn keeps normal subject–verb order.',{tokens:['Ich gehe,','denn','ich bin','müde.'],answer:['Ich gehe,','denn','ich bin','müde.']})]},
    'a1-life':{labels:{routines:'Daily routines',shopping:'Shopping',listening:'Listening strategies'},activities:[
      C('routine-order','routines','tokens','Build a routine','Build: I get up at seven.','Ich stehe um sieben auf.','aufstehen splits around the sentence.',{tokens:['Ich','stehe','um sieben','auf.'],answer:['Ich','stehe','um sieben','auf.']}),
      C('evening-cook','routines','choice','Use time-first order','Choose the natural sentence.','Abends koche ich.','The verb stays second after Abends.',{options:['Abends ich koche.','Abends koche ich.','Abends kochen ich.']}),
      C('try-on','shopping','choice','Ask in the shop','How do you ask to try clothing on?','Kann ich das anprobieren?','anprobieren means to try on.',{options:['Kann ich das anprobieren?','Was kostet an?','Ich probiere bezahlen.']}),
      C('pay-card','shopping','input','Complete the payment','Ich zahle mit ___.','Karte','mit Karte means by card.',{answers:['karte']}),
      C('listen-price-life','listening','listen','Catch the key detail','How much is it?','18,40 €','Catch the stressed price before translating anything else.',{audio:'Das macht achtzehn Euro vierzig.',options:['18,40 €','8,14 €','40,18 €']}),
      C('gist-first','listening','choice','Choose the strategy','What is the best first listening goal?','Catch the main situation','Understand gist before details.',{options:['Translate every word','Catch the main situation','Write every ending']}),
      C('slower','listening','dictation','Listen and type','Type the useful request Vivian says.','Bitte langsamer.','Use Bitte langsamer to control the conversation.',{audio:'Bitte langsamer.',answers:['bitte langsamer','bitte langsamer.']}),
      C('larger-size','shopping','tokens','Ask for another size','Build: Do you have that larger?','Haben Sie das größer?','This is a useful shop request.',{tokens:['Haben Sie','das','größer?'],answer:['Haben Sie','das','größer?']})]}
  };
  const config=configs[id],reviewId=page.searchParams.get('review'),reviewMode=Boolean(reviewId);let activities=config.activities;if(reviewMode){const item=reviewId.split(':')[2],found=activities.find(a=>a.id===item);if(found)activities=[found]}
  const box=document.querySelector('.quiz'),count=document.getElementById('qcount'),question=document.getElementById('question'),answers=document.getElementById('answers'),feedback=document.getElementById('feedback'),next=document.getElementById('next'),heading=document.querySelector('.practice h2');box.dataset.adaptive='true';heading.textContent=reviewMode?'One useful memory. Retrieve it now.':'Use it in life—not only in a quiz.';const kind=document.createElement('div'),mastery=document.createElement('div'),result=document.createElement('div');kind.id='labKind';mastery.className='syntax-mastery';result.className='syntax-result';count.after(kind);box.prepend(mastery);box.append(result);
  let index=Math.max(0,Math.min(activities.length-1,Number(page.searchParams.get('resume')||1)-1)),locked=false,started=performance.now(),results=[],api=null,baseline={};const ready=()=>new Promise(resolve=>{if(window.FallweiseProgress)resolve(window.FallweiseProgress);else addEventListener('fallweise:ready',e=>resolve(e.detail),{once:true})});ready().then(async value=>{api=value;const {data}=await api.client?.from('skill_mastery').select('*').like('skill_id',`lab-${id}:%`);(data||[]).forEach(row=>baseline[row.skill_id.split(':').pop()]=row);renderMastery()});const normalize=value=>value.trim().toLocaleLowerCase('de-DE').replace(/[.!?]/g,'').replace(/\s+/g,' ');function score(skill){const p=baseline[skill]||{attempts:0,correct_attempts:0},s=results.filter(r=>r.skill===skill),n=p.attempts+s.length,c=p.correct_attempts+s.filter(r=>r.correct).length;return n?Math.round(c/n*100):0}function renderMastery(){mastery.innerHTML=Object.entries(config.labels).map(([key,label])=>`<div><span>${label}</span><b>${score(key)}%</b></div>`).join('')}
  function render(){locked=false;started=performance.now();const a=activities[index];count.textContent=`ACTIVITY ${index+1} OF ${activities.length}`;kind.innerHTML=`<span class="syntax-kind">${a.kind}</span>`;question.textContent=a.prompt;answers.innerHTML='';feedback.textContent='';next.style.display='none';result.classList.remove('show');if(['listen','dictation'].includes(a.type))answers.insertAdjacentHTML('beforeend',`<div class="syntax-listen"><div class="german">${a.audio}</div></div>`);if(a.options)a.options.forEach(option=>{const b=document.createElement('button');b.className='answer';b.textContent=option;b.onclick=()=>submit(normalize(option)===normalize(a.correct),b,option);answers.appendChild(b)});else if(a.type==='tokens'){const drop=document.createElement('div'),bank=document.createElement('div'),check=document.createElement('button');drop.className='syntax-drop';bank.className='syntax-bank';check.className='syntax-check';check.textContent='Check';a.tokens.slice().sort(()=>Math.random()-.5).forEach(token=>{const b=document.createElement('button');b.type='button';b.className='syntax-token';b.textContent=token;b.onclick=()=>{(b.parentElement===bank?drop:bank).appendChild(b)};bank.appendChild(b)});check.onclick=()=>{const selected=[...drop.children].map(x=>x.textContent);submit(selected.join('|')===a.answer.join('|'),check,selected.join(' '))};answers.append(drop,bank,check)}else{const form=document.createElement('form');form.className='syntax-form';form.innerHTML='<input aria-label="Your answer" autocomplete="off" autocapitalize="none" required><button>Check</button>';form.onsubmit=e=>{e.preventDefault();const v=form.querySelector('input').value;submit(a.answers.some(x=>normalize(x)===normalize(v)),form.querySelector('input'),v)};answers.appendChild(form)}}
  async function submit(correct,target,selected){if(locked)return;locked=true;const a=activities[index],response_ms=Math.round(performance.now()-started);target.classList?.add(correct?'correct':'wrong');if(a.options)[...answers.querySelectorAll('.answer')].find(b=>normalize(b.textContent)===normalize(a.correct))?.classList.add('correct');feedback.textContent=(correct?'Richtig! ':'Not yet. ')+a.why+(correct?'':` Correct answer: ${a.correct}`);next.style.display='inline-block';next.disabled=true;next.textContent=index===activities.length-1?'See my result →':'Next activity →';results.push({skill:a.skill,correct});renderMastery();await save(a,correct,selected,response_ms);next.disabled=false}
  async function save(a,correct,selected,response_ms){api=api||await ready();const now=new Date().toISOString(),done=index===activities.length-1,lessonId=`skills:${id}`,skillId=`lab-${id}:${a.skill}`,masteryValue=results.filter(r=>r.correct).length/activities.length,operations=[];operations.push(api.recordAttempt({exercise_id:`lab:${id}:${a.id}`,skill_id:skillId,lesson_id:lessonId,exercise_type:a.type==='tokens'?'sentence_builder':a.type==='dictation'?'dictation':a.type==='input'?'fill_blank':a.type==='listen'?'listening':'choice',answer:{selected,prompt:a.prompt},correct,hints_used:0,response_ms,attempted_at:now}));if(!reviewMode)operations.push(api.saveLesson({lesson_id:lessonId,status:done?'completed':'in_progress',mastery:masteryValue,current_step:index+1,total_steps:activities.length,last_activity_at:now,...(index===0?{started_at:now}:{}),...(done?{completed_at:now}:{})}));const p=baseline[a.skill]||{attempts:0,correct_attempts:0,current_streak:0},s=results.filter(r=>r.skill===a.skill),attempts=p.attempts+s.length,correctAttempts=p.correct_attempts+s.filter(r=>r.correct).length,domain=id==='a1-sounds'?'pronunciation':a.skill==='listening'?'listening':id==='a1-life'?'vocabulary':'grammar';operations.push(api.saveSkill({skill_id:skillId,level:'A1',domain,mastery:correctAttempts/attempts,attempts,correct_attempts:correctAttempts,current_streak:correct?(p.current_streak||0)+1:0,last_practised_at:now}));const due=new Date(now);due.setMinutes(due.getMinutes()+(correct?1440:10));operations.push(api.saveReview({item_id:`lab:${id}:${a.id}`,skill_id:skillId,item_type:a.type==='dictation'?'spelling':a.type==='listen'?'listening':a.type==='tokens'?'sentence':'grammar',interval_days:correct?1:0,ease_factor:correct?2.5:2.3,repetitions:correct?1:0,lapses:correct?0:1,due_at:due.toISOString(),last_reviewed_at:now,suspended:false}));await Promise.all(operations)}
  function finish(){const correct=results.filter(r=>r.correct).length,weak=Object.keys(config.labels).sort((a,b)=>score(a)-score(b))[0];question.textContent='';answers.innerHTML='';feedback.textContent='';kind.innerHTML='';next.style.display='none';result.classList.add('show');result.innerHTML=reviewMode?`<div class="kicker">Review complete</div><h3>${correct?'Memory strengthened.':'A short retry is scheduled.'}</h3><a href="index.html">Back to today’s learning →</a>`:`<div class="kicker">Chapter complete</div><h3>${correct}/${activities.length} retrieved correctly</h3><p>Your current focus is <b>${config.labels[weak]}</b>. Review timing now reflects your answers.</p><a href="index.html">See progress and review queue →</a>`}next.onclick=()=>{if(!locked)return;if(index===activities.length-1)return finish();index++;render()};renderMastery();render();
})();
