(() => {
  const page=new URL(location.href),id=page.searchParams.get('id'),supported=['a1-sounds','a1-numbers','a1-conversations','a1-basics','a1-life','a2-past','a2-verb-preps','a2-questions','a2-adjectives','a2-life','b1-clauses','b1-precision','b1-prep-system','b1-passive-links','b1-exam'];if(!supported.includes(id))return;
  const C=(id,skill,type,kind,prompt,correct,why,extra={})=>({id,skill,type,kind,prompt,correct,why,...extra});
  const configs={
    'a1-sounds':{labels:{patterns:'Sound patterns',spelling:'Spelling',listening:'Listening'},activities:[
      C('ei-sound','patterns','choice','See the pattern','Which spelling usually sounds like English “eye”?','ei','ei sounds like “eye,” as in mein.',{options:['ie','ei','eu']}),
      C('umlaut-fallback','spelling','input','Type the fallback','Write ü when an umlaut keyboard is unavailable.','ue','German convention writes ü as ue.',{answers:['ue']}),
      C('listen-schön','listening','listen','Hear the umlaut','Which word did Vivian say?','schön','ö distinguishes schön from schon.',{audio:'schön',options:['schon','schön','Sohn']}),
      C('dictate-strasse','spelling','dictation','Listen and spell','Type the word Vivian says.','Straße','Straße uses initial Str- and ß.',{audio:'Straße',answers:['straße','strasse']}),
      C('ie-sound','patterns','choice','Contrast the pattern','Which spelling normally sounds like a long “ee”?','ie','ie is a long ee, as in Liebe.',{options:['ei','ie','eu']}),
      C('build-patterns','patterns','tokens','Build what you hear','Build: My friend plays today.','Mein Freund spielt heute.','The sentence contains ei, eu, sp, and eu sound patterns.',{tokens:['Mein Freund','spielt','heute.'],answer:['Mein Freund','spielt','heute.']}),
      C('listen-deutsch','listening','listen','Sound to word','Which word did Vivian say?','Deutsch','eu sounds like “oy.”',{audio:'Deutsch',options:['Deutsch','deutlich','dich']}),
      C('sharp-s','spelling','input','Recall the spelling','Complete: Grü__e','ß','Grüße uses ß after the long ü sound.',{answers:['ß','ss']})]},
    'a1-numbers':{labels:{numbers:'Numbers',time:'Time',dates:'Dates & prices'},activities:[
      C('twenty-four','numbers','input','Produce the number','Write 24 in German.','vierundzwanzig','German says four-and-twenty.',{answers:['vierundzwanzig']}),
      C('thirty-five','numbers','choice','Decode the order','What number is fünfunddreißig?','35','fünf-und-dreißig is five-and-thirty.',{options:['53','35','305']}),
      C('half-nine','time','choice','Read everyday time','What time is halb neun?','8:30','It is halfway toward nine.',{options:['9:30','8:30','8:09']}),
      C('build-time','time','tokens','Build the time','Build: It is quarter past eight.','Es ist Viertel nach acht.','Viertel nach means quarter past.',{tokens:['Es ist','Viertel nach','acht.'],answer:['Es ist','Viertel nach','acht.']}),
      C('listen-price','dates','listen','Catch the price','Which price did Vivian say?','18,40 €','Listen for achtzehn Euro vierzig.',{audio:'Das macht achtzehn Euro vierzig.',options:['18,40 €','80,40 €','18,14 €']}),
      C('may-third','dates','input','Produce the date','Complete: am ___ Mai (on May third)','dritten','After am, the ordinal uses -en.',{answers:['dritten']}),
      C('schedule','time','listen','Catch schedule time','When does the train leave?','16:12','The announcement says sechzehn Uhr zwölf.',{audio:'Der Zug fährt um sechzehn Uhr zwölf.',options:['16:12','6:20','17:16']}),
      C('ninety-nine','numbers','input','Transfer the pattern','Write 99 in German.','neunundneunzig','German says nine-and-ninety.',{answers:['neunundneunzig']})]},
    'a1-conversations':{labels:{register:'Formal & informal',politeness:'Polite phrases',imperative:'Instructions'},activities:[
      C('formal-name','register','choice','Choose the register','Which question is formal?','Wie heißen Sie?','Formal address uses Sie.',{options:['Wie heißt du?','Wie heißen Sie?','Wie heißt ihr?']}),
      C('introduction','register','input','Complete the introduction','Complete: Ich ___ Lina.','heiße','Ich heiße … introduces your name.',{answers:['heiße','heisse']}),
      C('polite-order','politeness','tokens','Build a polite order','Build: I would like a coffee.','Ich hätte gern einen Kaffee.','hätte gern is a natural polite request.',{tokens:['Ich','hätte gern','einen Kaffee.'],answer:['Ich','hätte gern','einen Kaffee.']}),
      C('listen-shop','politeness','listen','Hear the shop question','What did the seller ask?','Anything else?','Sonst noch etwas? means Anything else?',{audio:'Sonst noch etwas?',options:['Anything else?','How much is it?','Would you like coffee?']}),
      C('formal-wait','imperative','choice','Use the formal command','Formal “Wait!”','Warten Sie!','Formal imperative uses infinitive + Sie.',{options:['Warte!','Warten Sie!','Wartet du!']}),
      C('du-command','imperative','input','Produce the command','Informal singular: ___ bitte rein!','Komm','The du imperative of kommen is Komm!',{answers:['komm']}),
      C('listen-closing','politeness','listen','Recognize the closing','Which meaning matches what Vivian says?','No thanks, that is all.','This closes a purchase politely.',{audio:'Nein, danke. Das ist alles.',options:['No thanks, that is all.','Yes, one more thing.','Please repeat that.']}),
      C('nice-meet','register','choice','Close the introduction','What naturally means “Nice to meet you”?','Freut mich!','Freut mich is the natural short response.',{options:['Freut mich!','Gute Reise!','Keine Ursache!']})]},
    'a1-basics':{labels:{negation:'Negation',possessives:'Possessives',connectors:'Connectors'},activities:[
      C('keinen-hund','negation','input','Negate the noun','Complete: Ich habe ___ Hund.','keinen','Masculine accusative uses keinen.',{answers:['keinen']}),
      C('nicht-expensive','negation','tokens','Negate a quality','Build: That is not expensive.','Das ist nicht teuer.','nicht negates the adjective teuer.',{tokens:['Das','ist','nicht','teuer.'],answer:['Das','ist','nicht','teuer.']}),
      C('meine-sister','possessives','choice','Choose the possessive','Das ist ___ Schwester.','meine','Feminine nominative adds -e.',{options:['mein','meine','meinen']}),
      C('meinen-brother','possessives','input','Add the ending','Ich sehe ___ Bruder.','meinen','Masculine accusative adds -en.',{answers:['meinen']}),
      C('reason-denn','connectors','choice','Choose the relationship','Which connector gives a reason and keeps main-clause order?','denn','denn means because without moving the verb.',{options:['aber','denn','oder']}),
      C('listen-contrast','connectors','listen','Hear the relationship','Which sentence did Vivian say?','Es ist klein, aber schön.','aber marks a contrast.',{audio:'Es ist klein, aber schön.',options:['Es ist klein, aber schön.','Es ist klein oder schön.','Es ist klein denn schön.']}),
      C('kein-auto','negation','choice','Choose kein or nicht','Ich habe ___ Auto.','kein','Auto could take ein, so use kein.',{options:['nicht','keinen','kein']}),
      C('build-reason','connectors','tokens','Build a reason','Build: I am leaving because I am tired.','Ich gehe, denn ich bin müde.','denn keeps normal subject–verb order.',{tokens:['Ich gehe,','denn','ich bin','müde.'],answer:['Ich gehe,','denn','ich bin','müde.']})]},
    'a1-life':{labels:{routines:'Daily routines',shopping:'Shopping',listening:'Listening strategies'},activities:[
      C('routine-order','routines','tokens','Build a routine','Build: I get up at seven.','Ich stehe um sieben auf.','aufstehen splits around the sentence.',{tokens:['Ich','stehe','um sieben','auf.'],answer:['Ich','stehe','um sieben','auf.']}),
      C('evening-cook','routines','choice','Use time-first order','Choose the natural sentence.','Abends koche ich.','The verb stays second after Abends.',{options:['Abends ich koche.','Abends koche ich.','Abends kochen ich.']}),
      C('try-on','shopping','choice','Ask in the shop','How do you ask to try clothing on?','Kann ich das anprobieren?','anprobieren means to try on.',{options:['Kann ich das anprobieren?','Was kostet an?','Ich probiere bezahlen.']}),
      C('pay-card','shopping','input','Complete the payment','Ich zahle mit ___.','Karte','mit Karte means by card.',{answers:['karte']}),
      C('listen-price-life','listening','listen','Catch the key detail','How much is it?','18,40 €','Catch the stressed price before translating anything else.',{audio:'Das macht achtzehn Euro vierzig.',options:['18,40 €','8,14 €','40,18 €']}),
      C('gist-first','listening','choice','Choose the strategy','What is the best first listening goal?','Catch the main situation','Understand gist before details.',{options:['Translate every word','Catch the main situation','Write every ending']}),
      C('slower','listening','dictation','Listen and type','Type the useful request Vivian says.','Bitte langsamer.','Use Bitte langsamer to control the conversation.',{audio:'Bitte langsamer.',answers:['bitte langsamer','bitte langsamer.']}),
      C('larger-size','shopping','tokens','Ask for another size','Build: Do you have that larger?','Haben Sie das größer?','This is a useful shop request.',{tokens:['Haben Sie','das','größer?'],answer:['Haben Sie','das','größer?']})]},
    'a2-past':{level:'A2',labels:{past:'Simple past',modals:'Past modals',imperative:'Imperatives'},activities:[
      C('war-tired','past','choice','Choose the natural past','Yesterday I was tired.','Ich war gestern müde.','Spoken German normally uses war for past states.',{options:['Ich bin gestern müde.','Ich war gestern müde.','Ich hatte gestern müde.']}),
      C('hatte-time','past','input','Recall the form','Complete: Wir ___ keine Zeit.','hatten','haben becomes hatten in the simple past.',{answers:['hatten']}),
      C('build-problem','past','tokens','Build a past report','Build: There was a problem.','Es gab ein Problem.','es gab is the usual past form of es gibt.',{tokens:['Es','gab','ein Problem.'],answer:['Es','gab','ein Problem.']}),
      C('listen-couldnt','modals','listen','Hear past ability','Why did she not join us?','She could not come.','konnte expresses past ability or possibility.',{audio:'Sie konnte leider nicht kommen.',options:['She could not come.','She did not want to come.','She was not allowed to come.']}),
      C('had-to-wait','modals','input','Produce necessity','Complete: Ich ___ lange warten.','musste','Past necessity uses musste plus an infinitive.',{answers:['musste']}),
      C('wanted-eat','modals','tokens','Build a past intention','Build: We wanted to go out to eat.','Wir wollten essen gehen.','The conjugated modal is second; both infinitives finish the sentence.',{tokens:['Wir','wollten','essen gehen.'],answer:['Wir','wollten','essen gehen.']}),
      C('formal-careful','imperative','choice','Choose the register','Formal: Be careful!','Seien Sie vorsichtig!','The formal imperative of sein is Seien Sie.',{options:['Sei vorsichtig!','Seid vorsichtig!','Seien Sie vorsichtig!']}),
      C('listen-call','imperative','dictation','Hear useful advice','Type the advice Vivian says.','Ruf mich bitte an.','The separable prefix an closes the imperative.',{audio:'Ruf mich bitte an.',answers:['ruf mich bitte an','ruf mich bitte an.']})]},
    'a2-verb-preps':{level:'A2',labels:{partners:'Verb partners',questions:'Wo-compounds',reference:'Da-compounds'},activities:[
      C('wait-for','partners','choice','Recall the partner','Ich warte ___ den Zug.','auf','warten pairs with auf plus accusative.',{options:['an','auf','für']}),
      C('think-about','partners','input','Complete the package','Denkst du ___ mich?','an','denken pairs with an plus accusative.',{answers:['an']}),
      C('participate','partners','tokens','Build the verb frame','Build: He participates in the course.','Er nimmt an dem Kurs teil.','teilnehmen frames an + dative between nimmt and teil.',{tokens:['Er','nimmt','an dem Kurs','teil.'],answer:['Er','nimmt','an dem Kurs','teil.']}),
      C('listen-interest','partners','listen','Recognize the partner','What is she interested in?','Art','sich interessieren für introduces the interest.',{audio:'Sie interessiert sich für Kunst.',options:['Art','Sport','History']}),
      C('woran','questions','choice','Ask about a thing','What are you thinking about?','Woran denkst du?','wo + an becomes woran before a vowel.',{options:['Woran denkst du?','Wofür denkst du?','An wen denkst es?']}),
      C('worauf','questions','input','Form the question word','___ wartest du?','Worauf','warten auf becomes worauf for things.',{answers:['worauf']}),
      C('build-darauf','reference','tokens','Refer back naturally','Build: I am waiting for it.','Ich warte darauf.','A thing after warten auf becomes darauf.',{tokens:['Ich','warte','darauf.'],answer:['Ich','warte','darauf.']}),
      C('person-pronoun','reference','choice','Thing or person?','I speak with him.','Ich spreche mit ihm.','People keep the preposition plus personal pronoun.',{options:['Ich spreche damit.','Ich spreche mit ihm.','Ich spreche womit.']})]},
    'a2-questions':{level:'A2',labels:{indirect:'Indirect questions',whether:'Questions with ob',time:'Als or wenn'},activities:[
      C('when-train','indirect','tokens','Build a polite question','Build: Do you know when the train arrives?','Wissen Sie, wann der Zug kommt?','The embedded question sends kommt to the end.',{tokens:['Wissen Sie,','wann','der Zug','kommt?'],answer:['Wissen Sie,','wann','der Zug','kommt?']}),
      C('where-lives','indirect','input','Move the verb','Ich weiß nicht, wo er ___.','wohnt','The finite verb closes an indirect question.',{answers:['wohnt']}),
      C('listen-cost','indirect','listen','Catch the request','What information does the speaker want?','The price','wie viel das kostet asks for the price.',{audio:'Können Sie mir sagen, wie viel das kostet?',options:['The price','The departure time','The address']}),
      C('whether-open','whether','choice','Embed yes or no','I do not know whether it is open.','Ich weiß nicht, ob es offen ist.','Yes/no indirect questions begin with ob.',{options:['Ich weiß nicht, wenn es offen ist.','Ich weiß nicht, ob es offen ist.','Ich weiß nicht, als es offen ist.']}),
      C('build-ob','whether','tokens','Build an embedded question','Build: She asks whether we have time.','Sie fragt, ob wir Zeit haben.','ob introduces the clause and haben moves to the end.',{tokens:['Sie fragt,','ob','wir Zeit','haben.'],answer:['Sie fragt,','ob','wir Zeit','haben.']}),
      C('childhood-als','time','choice','One past period','___ ich klein war, wohnte ich in Bonn.','Als','A single past period uses als.',{options:['Wenn','Als','Ob']}),
      C('whenever-rain','time','input','Repeated past','Immer ___ es regnete, blieben wir zu Hause.','wenn','Repeated events use wenn—even in the past.',{answers:['wenn']}),
      C('listen-condition','time','listen','Hear the relationship','What should happen if you come?','Call me.','wenn introduces a future condition.',{audio:'Wenn du kommst, ruf mich an.',options:['Call me.','Wait outside.','Bring the train ticket.']})]},
    'a2-adjectives':{level:'A2',labels:{definite:'After der-words',indefinite:'After ein-words',strong:'Without an article'},activities:[
      C('der-dog','definite','choice','Choose the ending','der ___ Hund','kleine','Masculine nominative after der uses -e.',{options:['kleiner','kleine','kleinen']}),
      C('den-coat','definite','input','Mark accusative','Ich kaufe den ___ Mantel. (red)','roten','After den, the adjective uses -en.',{answers:['roten']}),
      C('build-dative-coat','definite','tokens','Build a dative phrase','Build: with the red coat','mit dem roten Mantel','After dem, the adjective uses -en.',{tokens:['mit','dem','roten','Mantel'],answer:['mit','dem','roten','Mantel']}),
      C('ein-book','indefinite','choice','Supply the signal','ein ___ Buch','interessantes','With bare ein, the adjective marks neuter with -es.',{options:['interessante','interessantes','interessanten']}),
      C('new-job','indefinite','input','Mark masculine','ein ___ Job (new)','neuer','The adjective supplies masculine nominative -er.',{answers:['neuer']}),
      C('listen-colleague','indefinite','listen','Hear the noun phrase','Which colleague is mentioned?','eine nette Kollegin','Feminine nominative uses eine nette.',{audio:'Das ist eine nette Kollegin.',options:['eine nette Kollegin','einen netten Kollegen','ein nettes Kind']}),
      C('cold-water','strong','choice','No article, full signal','mit ___ Wasser','kaltem','Without an article, neuter dative uses -em.',{options:['kaltes','kaltem','kalten']}),
      C('build-fresh-coffee','strong','tokens','Build a shopping phrase','Build: fresh coffee','frischer Kaffee','Without an article, masculine nominative uses -er.',{tokens:['frischer','Kaffee'],answer:['frischer','Kaffee']})]},
    'a2-life':{level:'A2',labels:{health:'Health',work:'Study & work',writing:'Reading & writing'},activities:[
      C('since-yesterday','health','choice','Describe duration','How do you say “since yesterday”?','seit gestern','seit marks something continuing until now.',{options:['für gestern','seit gestern','vor gestern']}),
      C('headache','health','input','Name the symptom','Ich habe ___. (a headache)','Kopfschmerzen','German commonly uses plural Kopfschmerzen.',{answers:['kopfschmerzen']}),
      C('listen-advice','health','listen','Understand advice','What should the patient do?','Drink plenty of water.','sollten softens medical advice.',{audio:'Sie sollten viel Wasser trinken.',options:['Drink plenty of water.','Take two tablets.','Stay at work.']}),
      C('reschedule','work','choice','Ask politely','Which request politely reschedules?','Könnten wir den Termin verschieben?','Könnten wir …? is polite and complete.',{options:['Termin ändern!','Könnten wir den Termin verschieben?','Ich will andere Zeit.']}),
      C('build-absence','work','tokens','Write a useful message','Build: Unfortunately I cannot come today.','Ich kann heute leider nicht kommen.','leider makes the absence message considerate.',{tokens:['Ich kann','heute','leider nicht','kommen.'],answer:['Ich kann','heute','leider nicht','kommen.']}),
      C('responsible','work','input','Describe a duty','Ich bin ___ Kunden zuständig.','für','zuständig pairs with für.',{answers:['für','fuer']}),
      C('reading-first','writing','choice','Read with purpose','What should you identify first?','Text type and purpose','Purpose tells you which details matter.',{options:['Every unknown noun','Text type and purpose','All adjective endings']}),
      C('listen-deadline','writing','dictation','Catch the required action','Type the notice Vivian says.','Bitte melden Sie sich bis Freitag an.','The notice contains an action and a Friday deadline.',{audio:'Bitte melden Sie sich bis Freitag an.',answers:['bitte melden sie sich bis freitag an','bitte melden sie sich bis freitag an.']})]},
    'b1-clauses':{level:'B1',labels:{relative:'Relative clauses',infinitive:'Zu-infinitives',choice:'Zu or dass'},activities:[
      C('relative-subject','relative','choice','Find the clause job','Die Frau, ___ dort steht, ist Ärztin.','die','The woman is the subject inside the relative clause.',{options:['die','der','deren']}),
      C('relative-dative','relative','input','Let the verb choose','Die Frau, ___ ich helfe, ist nett.','der','helfen requires dative, so feminine becomes der.',{answers:['der']}),
      C('relative-prep','relative','tokens','Build the relationship','Build: The colleague with whom I work is friendly.','Der Kollege, mit dem ich arbeite, ist freundlich.','mit requires dative; masculine dative relative pronoun is dem.',{tokens:['Der Kollege,','mit dem','ich arbeite,','ist freundlich.'],answer:['Der Kollege,','mit dem','ich arbeite,','ist freundlich.']}),
      C('listen-possession','relative','listen','Hear possession','Whose car is broken?','The woman’s car','deren expresses feminine possession.',{audio:'Die Frau, deren Auto kaputt ist, wartet draußen.',options:['The woman’s car','The man’s bicycle','The colleague’s phone']}),
      C('plan-move','infinitive','choice','Place zu correctly','Er plant, morgen ___.','umzuziehen','zu enters the middle of the separable verb umziehen.',{options:['zu umziehen','umzuziehen','dass umzieht']}),
      C('try-sleep','infinitive','input','Complete the infinitive','Ich versuche, früher zu ___.','schlafen','A shared subject allows a zu-infinitive.',{answers:['schlafen']}),
      C('different-subject','choice','tokens','Build with dass','Build: I hope that you come.','Ich hoffe, dass du kommst.','Different explicit subjects require a dass-clause.',{tokens:['Ich hoffe,','dass','du','kommst.'],answer:['Ich hoffe,','dass','du','kommst.']}),
      C('listen-important','choice','dictation','Hear the shared-subject form','Type the sentence Vivian says.','Es ist wichtig, gut zuzuhören.','A general evaluation uses a zu-infinitive.',{audio:'Es ist wichtig, gut zuzuhören.',answers:['es ist wichtig gut zuzuhören','es ist wichtig, gut zuzuhören','es ist wichtig, gut zuzuhören.']})]},
    'b1-precision':{level:'B1',labels:{nouns:'N-declension',endings:'Advanced endings',parallel:'Parallel forms'},activities:[
      C('student-acc','nouns','choice','Decline the person','Ich sehe den ___.','Studenten','Student gains -en outside nominative singular.',{options:['Student','Studenten','Students']}),
      C('colleague-dative','nouns','input','Complete the noun','Ich spreche mit dem ___.','Kollegen','Kollege gains -n in dative.',{answers:['kollegen']}),
      C('expert-genitive','nouns','tokens','Build possession','Build: the expert’s opinion','die Meinung des Experten','Experte gains -n in genitive.',{tokens:['die Meinung','des','Experten'],answer:['die Meinung','des','Experten']}),
      C('listen-president','nouns','listen','Hear the declined noun','Who did she speak with?','The president','Präsident is an N-declension noun.',{audio:'Sie sprach mit dem Präsidenten.',options:['The president','The student','The customer']}),
      C('large-problem','endings','choice','Read the determiner signal','trotz eines ___ Problems','großen','After genitive eines, the adjective takes -en.',{options:['großes','großen','großer']}),
      C('heavy-rain','endings','input','Use a strong ending','wegen ___ Regenfälle (heavy)','starker','Without an article, plural genitive uses -er.',{answers:['starker']}),
      C('working-system','parallel','choice','Turn a participle into an adjective','ein gut ___ System','funktionierendes','Neuter nominative after ein requires -es.',{options:['funktionierende','funktionierendes','funktionierenden']}),
      C('experienced-colleagues','parallel','tokens','Coordinate two adjectives','Build: with experienced German colleagues','mit erfahrenen deutschen Kollegen','Both adjectives share plural dative -en.',{tokens:['mit','erfahrenen','deutschen','Kollegen'],answer:['mit','erfahrenen','deutschen','Kollegen']})]},
    'b1-prep-system':{level:'B1',labels:{packages:'Fixed packages',reference:'Da-compounds',questions:'Question pairs'},activities:[
      C('depends-weather','packages','choice','Recall case and partner','Das hängt ___ Wetter ab.','vom','abhängen pairs with von plus dative.',{options:['auf dem','vom','für das']}),
      C('interest-topic','packages','input','Complete the noun package','Sie hat Interesse ___ Politik.','an','Interesse pairs with an plus dative.',{answers:['an']}),
      C('responsible-project','packages','tokens','Build the adjective package','Build: He is responsible for the project.','Er ist für das Projekt verantwortlich.','verantwortlich pairs with für plus accusative.',{tokens:['Er ist','für das Projekt','verantwortlich.'],answer:['Er ist','für das Projekt','verantwortlich.']}),
      C('listen-proud','packages','listen','Recognize the package','What is she proud of?','Her result','stolz pairs with auf.',{audio:'Sie ist stolz auf ihr Ergebnis.',options:['Her result','Her colleague','The weather']}),
      C('expect-it','reference','choice','Replace a thing','I expect it.','Ich rechne damit.','rechnen mit becomes damit for a thing.',{options:['Ich rechne davon.','Ich rechne damit.','Ich rechne darauf.']}),
      C('depends-that','reference','input','Refer back','___ hängt alles ab.','Davon','abhängen von becomes davon.',{answers:['davon']}),
      C('proud-question','questions','tokens','Build the mirrored question','Build: What are you proud of?','Worauf bist du stolz?','stolz auf becomes worauf for things.',{tokens:['Worauf','bist du','stolz?'],answer:['Worauf','bist du','stolz?']}),
      C('person-question','questions','choice','Ask about a person','Whom are you waiting for?','Auf wen wartest du?','People use preposition plus wen, not worauf.',{options:['Worauf wartest du?','Auf wen wartest du?','Womit wartest du?']})]},
    'b1-passive-links':{level:'B1',labels:{passive:'Passive tenses',modal:'Modal passive',connectors:'Advanced connectors'},activities:[
      C('bridge-present','passive','choice','Identify present passive','The bridge is being built.','Die Brücke wird gebaut.','Present passive uses wird plus participle.',{options:['Die Brücke wird gebaut.','Die Brücke wurde gebaut.','Die Brücke hat gebaut.']}),
      C('email-past','passive','input','Produce past passive','Die E-Mail ___ geschickt.','wurde','Präteritum passive uses wurde plus participle.',{answers:['wurde']}),
      C('perfect-passive','passive','tokens','Build completed passive','Build: The bridge has been built.','Die Brücke ist gebaut worden.','Perfect passive ends with participle plus worden.',{tokens:['Die Brücke','ist','gebaut','worden.'],answer:['Die Brücke','ist','gebaut','worden.']}),
      C('listen-repaired','modal','listen','Hear necessity','What must happen?','It must be repaired.','Modal passive uses muss + participle + werden.',{audio:'Das muss sofort repariert werden.',options:['It must be repaired.','It may be opened.','It was already repaired.']}),
      C('rules-explained','modal','input','Complete the passive frame','Die Regeln sollten erklärt ___.','werden','The modal passive closes with werden.',{answers:['werden']}),
      C('cannot-open','modal','tokens','Build a prohibition','Build: It may not be opened.','Es darf nicht geöffnet werden.','Modal + nicht + participle + werden forms the prohibition.',{tokens:['Es darf','nicht','geöffnet','werden.'],answer:['Es darf','nicht','geöffnet','werden.']}),
      C('method-indem','connectors','choice','Express a method','Which connector means “by doing”?','indem','indem introduces the method used.',{options:['falls','indem','sobald']}),
      C('listen-sequence','connectors','dictation','Hear immediate sequence','Type the sentence Vivian says.','Sobald ich ankomme, rufe ich an.','sobald marks an action that follows immediately.',{audio:'Sobald ich ankomme, rufe ich an.',answers:['sobald ich ankomme rufe ich an','sobald ich ankomme, rufe ich an','sobald ich ankomme, rufe ich an.']})]},
    'b1-exam':{level:'B1',labels:{vocabulary:'Useful collocations',structure:'Coherent production',strategy:'Exam communication'},activities:[
      C('decision','vocabulary','choice','Choose the collocation','Which phrase is natural?','eine Entscheidung treffen','German uses treffen with Entscheidung.',{options:['eine Entscheidung machen','eine Entscheidung treffen','eine Entscheidung tun']}),
      C('responsibility','vocabulary','input','Complete the collocation','Verantwortung ___.','übernehmen','Verantwortung übernehmen means to take responsibility.',{answers:['übernehmen','uebernehmen']}),
      C('save-energy','vocabulary','tokens','Build the environmental phrase','Build: We should save energy.','Wir sollten Energie sparen.','Energie sparen is the standard collocation.',{tokens:['Wir sollten','Energie','sparen.'],answer:['Wir sollten','Energie','sparen.']}),
      C('listen-example','structure','listen','Identify the discourse move','What comes next?','An example','Ein Beispiel dafür ist introduces supporting evidence.',{audio:'Ein Beispiel dafür ist der öffentliche Nahverkehr.',options:['An example','A conclusion','A disagreement']}),
      C('balanced-view','structure','choice','Signal two sides','Which phrase introduces a balanced contrast?','Einerseits …, andererseits …','The pair organizes two opposing perspectives.',{options:['Zum Beispiel …','Einerseits …, andererseits …','Abschließend …']}),
      C('conclusion','structure','input','Complete the formal ending','___ lässt sich sagen, dass …','Abschließend','Abschließend signals the conclusion.',{answers:['abschließend','abschliessend']}),
      C('repair-phrase','strategy','choice','Keep communication moving','Which phrase checks understanding?','Wenn ich Sie richtig verstanden habe, …','It confirms meaning while continuing the conversation.',{options:['Keine Ahnung.','Wenn ich Sie richtig verstanden habe, …','Ich kann nicht Deutsch.']}),
      C('listen-request','strategy','dictation','Hear a formal request','Type the sentence Vivian says.','Könnten Sie mir bitte mitteilen, wann der Kurs beginnt?','The phrase states a complete, polite information request.',{audio:'Könnten Sie mir bitte mitteilen, wann der Kurs beginnt?',answers:['könnten sie mir bitte mitteilen wann der kurs beginnt','könnten sie mir bitte mitteilen, wann der kurs beginnt','könnten sie mir bitte mitteilen, wann der kurs beginnt?']})]}
  };
  const config=configs[id],reviewId=page.searchParams.get('review'),reviewMode=Boolean(reviewId);let activities=config.activities;if(reviewMode){const item=reviewId.split(':')[2],found=activities.find(a=>a.id===item);if(found)activities=[found]}
  const box=document.querySelector('.quiz'),count=document.getElementById('qcount'),question=document.getElementById('question'),answers=document.getElementById('answers'),feedback=document.getElementById('feedback'),next=document.getElementById('next'),heading=document.querySelector('.practice h2');box.dataset.adaptive='true';heading.textContent=reviewMode?'One useful memory. Retrieve it now.':'Use it in life—not only in a quiz.';const kind=document.createElement('div'),mastery=document.createElement('div'),result=document.createElement('div');kind.id='labKind';mastery.className='syntax-mastery';result.className='syntax-result';count.after(kind);box.prepend(mastery);box.append(result);
  let index=Math.max(0,Math.min(activities.length-1,Number(page.searchParams.get('resume')||1)-1)),locked=false,started=performance.now(),results=[],api=null,baseline={};const ready=()=>new Promise(resolve=>{if(window.FallweiseProgress)resolve(window.FallweiseProgress);else addEventListener('fallweise:ready',e=>resolve(e.detail),{once:true})});ready().then(async value=>{api=value;const {data}=await api.client?.from('skill_mastery').select('*').like('skill_id',`lab-${id}:%`);(data||[]).forEach(row=>baseline[row.skill_id.split(':').pop()]=row);renderMastery()});const normalize=value=>value.trim().toLocaleLowerCase('de-DE').replace(/[.!?]/g,'').replace(/\s+/g,' ');function score(skill){const p=baseline[skill]||{attempts:0,correct_attempts:0},s=results.filter(r=>r.skill===skill),n=p.attempts+s.length,c=p.correct_attempts+s.filter(r=>r.correct).length;return n?Math.round(c/n*100):0}function renderMastery(){mastery.innerHTML=Object.entries(config.labels).map(([key,label])=>`<div><span>${label}</span><b>${score(key)}%</b></div>`).join('')}
  function render(){locked=false;started=performance.now();const a=activities[index];count.textContent=`ACTIVITY ${index+1} OF ${activities.length}`;kind.innerHTML=`<span class="syntax-kind">${a.kind}</span>`;question.textContent=a.prompt;answers.innerHTML='';feedback.textContent='';next.style.display='none';result.classList.remove('show');if(['listen','dictation'].includes(a.type))answers.insertAdjacentHTML('beforeend',`<div class="syntax-listen"><div class="german">${a.audio}</div></div>`);if(a.options)a.options.forEach(option=>{const b=document.createElement('button');b.className='answer';b.textContent=option;b.onclick=()=>submit(normalize(option)===normalize(a.correct),b,option);answers.appendChild(b)});else if(a.type==='tokens'){const drop=document.createElement('div'),bank=document.createElement('div'),check=document.createElement('button');drop.className='syntax-drop';bank.className='syntax-bank';check.className='syntax-check';check.textContent='Check';a.tokens.slice().sort(()=>Math.random()-.5).forEach(token=>{const b=document.createElement('button');b.type='button';b.className='syntax-token';b.textContent=token;b.onclick=()=>{(b.parentElement===bank?drop:bank).appendChild(b)};bank.appendChild(b)});check.onclick=()=>{const selected=[...drop.children].map(x=>x.textContent);submit(selected.join('|')===a.answer.join('|'),check,selected.join(' '))};answers.append(drop,bank,check)}else{const form=document.createElement('form');form.className='syntax-form';form.innerHTML='<input aria-label="Your answer" autocomplete="off" autocapitalize="none" required><button>Check</button>';form.onsubmit=e=>{e.preventDefault();const v=form.querySelector('input').value;submit(a.answers.some(x=>normalize(x)===normalize(v)),form.querySelector('input'),v)};answers.appendChild(form)}}
  async function submit(correct,target,selected){if(locked)return;locked=true;const a=activities[index],response_ms=Math.round(performance.now()-started);target.classList?.add(correct?'correct':'wrong');if(a.options)[...answers.querySelectorAll('.answer')].find(b=>normalize(b.textContent)===normalize(a.correct))?.classList.add('correct');feedback.textContent=(correct?'Richtig! ':'Not yet. ')+a.why+(correct?'':` Correct answer: ${a.correct}`);next.style.display='inline-block';next.disabled=true;next.textContent=index===activities.length-1?'See my result →':'Next activity →';results.push({skill:a.skill,correct});renderMastery();await save(a,correct,selected,response_ms);next.disabled=false}
  async function save(a,correct,selected,response_ms){api=api||await ready();const now=new Date().toISOString(),done=index===activities.length-1,lessonId=`skills:${id}`,skillId=`lab-${id}:${a.skill}`,masteryValue=results.filter(r=>r.correct).length/activities.length,operations=[];operations.push(api.recordAttempt({exercise_id:`lab:${id}:${a.id}`,skill_id:skillId,lesson_id:lessonId,exercise_type:a.type==='tokens'?'sentence_builder':a.type==='dictation'?'dictation':a.type==='input'?'fill_blank':a.type==='listen'?'listening':'choice',answer:{selected,prompt:a.prompt},correct,hints_used:0,response_ms,attempted_at:now}));if(!reviewMode)operations.push(api.saveLesson({lesson_id:lessonId,status:done?'completed':'in_progress',mastery:masteryValue,current_step:index+1,total_steps:activities.length,last_activity_at:now,...(index===0?{started_at:now}:{}),...(done?{completed_at:now}:{})}));const p=baseline[a.skill]||{attempts:0,correct_attempts:0,current_streak:0},s=results.filter(r=>r.skill===a.skill),attempts=p.attempts+s.length,correctAttempts=p.correct_attempts+s.filter(r=>r.correct).length,domain=id==='a1-sounds'?'pronunciation':a.skill==='listening'?'listening':id.endsWith('-life')?'vocabulary':'grammar';operations.push(api.saveSkill({skill_id:skillId,level:config.level||'A1',domain,mastery:correctAttempts/attempts,attempts,correct_attempts:correctAttempts,current_streak:correct?(p.current_streak||0)+1:0,last_practised_at:now}));const due=new Date(now);due.setMinutes(due.getMinutes()+(correct?1440:10));operations.push(api.saveReview({item_id:`lab:${id}:${a.id}`,skill_id:skillId,item_type:a.type==='dictation'?'spelling':a.type==='listen'?'listening':a.type==='tokens'?'sentence':'grammar',interval_days:correct?1:0,ease_factor:correct?2.5:2.3,repetitions:correct?1:0,lapses:correct?0:1,due_at:due.toISOString(),last_reviewed_at:now,suspended:false}));await Promise.all(operations)}
  function finish(){const correct=results.filter(r=>r.correct).length,weak=Object.keys(config.labels).sort((a,b)=>score(a)-score(b))[0];question.textContent='';answers.innerHTML='';feedback.textContent='';kind.innerHTML='';next.style.display='none';result.classList.add('show');result.innerHTML=reviewMode?`<div class="kicker">Review complete</div><h3>${correct?'Memory strengthened.':'A short retry is scheduled.'}</h3><a href="index.html">Back to today’s learning →</a>`:`<div class="kicker">Chapter complete</div><h3>${correct}/${activities.length} retrieved correctly</h3><p>Your current focus is <b>${config.labels[weak]}</b>. Review timing now reflects your answers.</p><a href="index.html">See progress and review queue →</a>`}next.onclick=()=>{if(!locked)return;if(index===activities.length-1)return finish();index++;render()};renderMastery();render();
})();
