(() => {
  if(new URLSearchParams(location.search).get('level')!=='a1')return;
  const skillLabels={roles:'Case jobs',articles:'Article forms',order:'Sentence control'};
  let activities=[
    {id:'find-doer',skill:'roles',type:'choice',kind:'Notice the job',prompt:'In “Heute besucht uns die Lehrerin,” who is doing the action?',options:['Heute','uns','die Lehrerin'],answer:2,why:'Word position can move. Die Lehrerin performs besucht.',review:'find-the-doer'},
    {id:'find-target',skill:'roles',type:'choice',kind:'Spot the target',prompt:'In “Der Hund sieht den Mann,” what receives the action?',options:['der Hund','den Mann','sieht'],answer:1,why:'The man is directly seen, so den Mann is accusative.',review:'find-the-target'},
    {id:'masculine-article',skill:'articles',type:'input',kind:'Produce it',prompt:'Complete the sentence: Ich sehe ___ Mann.',answers:['den'],display:'den',why:'Masculine der changes to den as a direct object.',review:'der-becomes-den'},
    {id:'indefinite-article',skill:'articles',type:'input',kind:'Recall the form',prompt:'Complete: Ein Hund jagt ___ Ball.',answers:['einen'],display:'einen',why:'Masculine ein changes to einen in the accusative.',review:'ein-becomes-einen'},
    {id:'build-sentence',skill:'order',type:'tokens',kind:'Build a sentence',prompt:'Build: The woman buys the bag.',tokens:['Die Frau','kauft','die Tasche'],answer:['Die Frau','kauft','die Tasche'],why:'The doer comes with nominative die; feminine die stays die as the object.',review:'build-subject-object'},
    {id:'pronoun-object',skill:'articles',type:'choice',kind:'Change the pronoun',prompt:'Complete: Sie kennt ___.',options:['er','ihn','ihm'],answer:1,why:'er becomes ihn when he is the direct object.',review:'er-becomes-ihn'},
    {id:'correct-error',skill:'order',type:'choice',kind:'Correct the error',prompt:'Which sentence means “A dog chases a ball”?',options:['Einen Hund jagt ein Ball.','Ein Hund jagt einen Ball.','Ein Hund jagt einem Ball.'],answer:1,why:'Ein Hund is the doer; einen Ball is the direct target.',review:'correct-case-signals'},
    {id:'transfer',skill:'roles',type:'input',kind:'Use the pattern',prompt:'Complete with one word: Der Junge liebt ___ Hund.',answers:['den','seinen','einen'],display:'den / seinen / einen',why:'Hund is masculine and directly affected, so its article carries accusative -n.',review:'transfer-masculine-object'}
  ];
  const els={quiz:document.getElementById('quiz'),count:document.getElementById('qcount'),kind:document.getElementById('exerciseKind'),question:document.getElementById('question'),answers:document.getElementById('answers'),feedback:document.getElementById('feedback'),next:document.getElementById('next'),mastery:document.getElementById('mastery'),result:document.getElementById('resultPanel'),title:document.getElementById('practiceTitle')};
  let index=0,locked=false,started=performance.now(),results=[],api=null;
  const params=new URLSearchParams(location.search),reviewId=params.get('review'),reviewMode=Boolean(reviewId);if(reviewId){const found=activities.find(a=>reviewId.endsWith(a.review));if(found)activities=[found]}
  els.quiz.dataset.adaptive='true';els.mastery.classList.add('show');els.title.textContent=reviewMode?'Retrieve it once. Strengthen it.':'Use the case—not just recognize it.';
  const ready=()=>new Promise(resolve=>{if(window.FallweiseProgress)resolve(window.FallweiseProgress);else addEventListener('fallweise:ready',e=>resolve(e.detail),{once:true})});
  const normalize=value=>value.trim().toLocaleLowerCase('de-DE').replace(/[.!?]/g,'').replace(/\s+/g,' ');
  function masteryValue(skill){const attempts=results.filter(r=>r.skill===skill);return attempts.length?Math.round(attempts.filter(r=>r.correct).length/attempts.length*100):0}
  function renderMastery(){els.mastery.innerHTML=Object.entries(skillLabels).map(([key,label])=>`<div class="mastery-item"><span>${label}</span><b>${masteryValue(key)}%</b></div>`).join('')}
  function render(){locked=false;started=performance.now();const activity=activities[index];els.count.textContent=`ACTIVITY ${index+1} OF ${activities.length}`;els.kind.innerHTML=`<span class="exercise-kind">${activity.kind}</span>`;els.question.textContent=activity.prompt;els.answers.innerHTML='';els.feedback.textContent='';els.next.style.display='none';els.result.classList.remove('show');
    if(activity.type==='choice')activity.options.forEach((option,i)=>{const button=document.createElement('button');button.className='answer';button.textContent=option;button.onclick=()=>submit(i===activity.answer,button,option);els.answers.appendChild(button)});
    if(activity.type==='input'){els.answers.innerHTML='<form class="text-answer"><input aria-label="Your answer" autocomplete="off" autocapitalize="none" required><button>Check</button></form>';const form=els.answers.querySelector('form');form.onsubmit=e=>{e.preventDefault();const value=form.querySelector('input').value;submit(activity.answers.includes(normalize(value)),form.querySelector('input'),value)}}
    if(activity.type==='tokens'){const drop=document.createElement('div'),bank=document.createElement('div'),check=document.createElement('button');drop.className='sentence-drop';bank.className='token-bank';check.className='token-check';check.textContent='Check sentence';activity.tokens.slice().sort(()=>.5-Math.random()).forEach(token=>{const button=document.createElement('button');button.type='button';button.className='token';button.textContent=token;button.onclick=()=>{(button.parentElement===bank?drop:bank).appendChild(button)};bank.appendChild(button)});els.answers.append(drop,bank,check);check.onclick=()=>{const selected=[...drop.children].map(x=>x.textContent);submit(selected.join('|')===activity.answer.join('|'),check,selected.join(' '))}}
  }
  async function submit(correct,target,selected){if(locked)return;locked=true;const activity=activities[index],elapsed=Math.round(performance.now()-started);if(target.classList)target.classList.add(correct?'correct':'wrong');if(activity.type==='choice')els.answers.children[activity.answer]?.classList.add('correct');els.feedback.textContent=(correct?'Richtig! ':'Not yet. ')+activity.why+(correct?'':' Correct answer: '+(activity.display||activity.options?.[activity.answer]||activity.answer.join(' '))+'.');els.next.style.display='inline-block';els.next.textContent=index===activities.length-1?'See my result →':'Next activity →';results.push({skill:activity.skill,correct});renderMastery();await save(activity,correct,selected,elapsed)}
  async function save(activity,correct,selected,response_ms){api=api||await ready();const now=new Date().toISOString(),done=index===activities.length-1,mastery=results.filter(r=>r.correct).length/activities.length;api.recordAttempt({exercise_id:`a1-cases:${activity.id}`,skill_id:`a1-cases:${activity.skill}`,lesson_id:'cases:a1',exercise_type:activity.type==='tokens'?'sentence_builder':activity.type==='input'?'fill_blank':'choice',answer:{selected,prompt:activity.prompt},correct,hints_used:0,response_ms,attempted_at:now});if(!reviewMode)api.saveLesson({lesson_id:'cases:a1',status:done?'completed':'in_progress',mastery,current_step:index+1,total_steps:activities.length,last_activity_at:now,...(index===0?{started_at:now}:{}),...(done?{completed_at:now}:{})});const skillResults=results.filter(r=>r.skill===activity.skill),correctAttempts=skillResults.filter(r=>r.correct).length;api.saveSkill({skill_id:`a1-cases:${activity.skill}`,level:'A1',domain:'grammar',mastery:correctAttempts/skillResults.length,attempts:skillResults.length,correct_attempts:correctAttempts,current_streak:correct?skillResults.slice().reverse().findIndex(r=>!r.correct)<0?skillResults.length:skillResults.slice().reverse().findIndex(r=>!r.correct):0,last_practised_at:now});scheduleReview(activity,correct,now)}
  function scheduleReview(activity,correct,now){const due=new Date(now);due.setMinutes(due.getMinutes()+(correct?24*60:10));api.saveReview({item_id:`a1-cases:${activity.review}`,skill_id:`a1-cases:${activity.skill}`,item_type:activity.type==='tokens'?'sentence':'grammar',interval_days:correct?1:0,ease_factor:correct?2.5:2.3,repetitions:correct?1:0,lapses:correct?0:1,due_at:due.toISOString(),last_reviewed_at:now,suspended:false})}
  function finish(){const correct=results.filter(r=>r.correct).length,weak=Object.keys(skillLabels).sort((a,b)=>masteryValue(a)-masteryValue(b))[0];els.question.textContent='';els.answers.innerHTML='';els.feedback.textContent='';els.kind.innerHTML='';els.next.style.display='none';els.result.classList.add('show');els.result.innerHTML=reviewMode?`<div class="kicker" style="color:var(--lime)">Review complete</div><h3>${correct?'Memory strengthened.':'We’ll bring it back soon.'}</h3><p>${correct?'Successful retrieval moves this item to tomorrow.':'A short retry is scheduled so the pattern has another chance to stick.'}</p><a href="index.html">Back to today’s learning →</a>`:`<div class="kicker" style="color:var(--lime)">Lesson complete</div><h3>${correct}/${activities.length} retrieved correctly</h3><p>Your current focus is <b>${skillLabels[weak]}</b>. Missed patterns are now scheduled for short review.</p><a href="index.html">See progress and review queue →</a>`}
  els.next.onclick=()=>{if(index===activities.length-1)return finish();index++;render()};renderMastery();render();
})();
