(() => {
  const Q=(id,domain,type,prompt,correct,extra={})=>({id,domain,type,prompt,correct,...extra});
  const sets={
    A1:[
      Q('vocab-home','vocabulary','choice','What does “der Kühlschrank” mean?','refrigerator',{options:['refrigerator','wardrobe','stove']}),Q('vocab-shop','vocabulary','input','Type the German noun for “bread” with its article.','das Brot',{answers:['das brot']}),
      Q('grammar-acc','grammar','choice','Ich sehe ___ Mann.','den',{options:['der','den','dem']}),Q('grammar-order','grammar','tokens','Build: Today she works at home.','Heute arbeitet sie zu Hause.',{tokens:['Heute','arbeitet','sie','zu Hause.']}),
      Q('listen-time','listening','listen','When does the appointment begin?','3:30 p.m.',{audio:'Der Termin beginnt um halb vier.',options:['3:30 p.m.','4:30 p.m.','3:15 p.m.']}),Q('listen-shop','listening','listen','What does the customer want?','A coffee',{audio:'Ich hätte gern einen Kaffee, bitte.',options:['A coffee','A ticket','A table']}),
      Q('read-notice','reading','choice','When is the shop closed?','Sunday',{passage:'Öffnungszeiten: Montag bis Samstag, 9–18 Uhr. Sonntag geschlossen.',options:['Monday','Saturday','Sunday']}),Q('read-message','reading','choice','Where will Lea wait?','At the station',{passage:'Hallo Tom, mein Zug kommt um 18 Uhr an. Ich warte vor dem Bahnhof. Bis später! Lea',options:['At the station','At home','At the café']}),
      Q('produce-modal','production','tokens','Build: I can speak a little German.','Ich kann ein bisschen Deutsch sprechen.',{tokens:['Ich','kann','ein bisschen Deutsch','sprechen.']}),Q('produce-question','production','input','Complete the polite question: Wie viel ___ das?','kostet',{answers:['kostet']})],
    A2:[
      Q('vocab-health','vocabulary','choice','What does “Kopfschmerzen” mean?','headache',{options:['headache','sore throat','fever']}),Q('vocab-work','vocabulary','input','Complete: einen Termin ___. (reschedule)','verschieben',{answers:['verschieben']}),
      Q('grammar-clause','grammar','choice','Ich bleibe zu Hause, weil ___.','ich krank bin',{options:['ich bin krank','ich krank bin','bin ich krank']}),Q('grammar-past','grammar','tokens','Build: We had no time.','Wir hatten keine Zeit.',{tokens:['Wir','hatten','keine Zeit.']}),
      Q('listen-train','listening','listen','What should passengers do?','Use platform four',{audio:'Der Zug nach Hamburg fährt heute von Gleis vier ab.',options:['Use platform four','Wait twenty minutes','Change in Hamburg']}),Q('listen-doctor','listening','listen','What advice is given?','Drink plenty of water',{audio:'Sie sollten viel Wasser trinken und sich ausruhen.',options:['Drink plenty of water','Return to work','Take the train']}),
      Q('read-course','reading','choice','What must participants do by Friday?','Register',{passage:'Der Computerkurs beginnt am 12. Mai. Bitte melden Sie sich bis Freitag online an.',options:['Register','Pay in cash','Bring a computer']}),Q('read-reschedule','reading','choice','Why is the meeting changing?','The writer is ill',{passage:'Leider bin ich krank und kann morgen nicht kommen. Können wir unseren Termin auf Donnerstag verschieben?',options:['The writer is ill','The office is closed','The train is late']}),
      Q('produce-perfect','production','tokens','Build: I have already booked the room.','Ich habe das Zimmer schon gebucht.',{tokens:['Ich','habe','das Zimmer','schon','gebucht.']}),Q('produce-indirect','production','input','Complete: Wissen Sie, wann der Zug ___?','kommt',{answers:['kommt']})],
    B1:[
      Q('vocab-decision','vocabulary','choice','Choose the natural collocation.','eine Entscheidung treffen',{options:['eine Entscheidung machen','eine Entscheidung treffen','eine Entscheidung tun']}),Q('vocab-responsibility','vocabulary','input','Complete: Verantwortung ___.','übernehmen',{answers:['übernehmen','uebernehmen']}),
      Q('grammar-relative','grammar','choice','Die Kollegin, mit ___ ich arbeite, ist sehr erfahren.','der',{options:['die','der','deren']}),Q('grammar-passive','grammar','tokens','Build: The documents must be signed.','Die Dokumente müssen unterschrieben werden.',{tokens:['Die Dokumente','müssen','unterschrieben','werden.']}),
      Q('listen-opinion','listening','listen','What is the speaker’s position?','Public transport should be improved',{audio:'Meiner Meinung nach sollte der öffentliche Nahverkehr verbessert werden.',options:['Public transport should be improved','Cars should be cheaper','The project should stop']}),Q('listen-process','listening','listen','What has already happened?','The application was checked',{audio:'Der Antrag ist bereits geprüft worden.',options:['The application was checked','The application is missing','The deadline changed']}),
      Q('read-work','reading','choice','What is the main advantage?','Flexible working time',{passage:'Die Stelle bietet flexible Arbeitszeiten und zwei Homeoffice-Tage pro Woche. Berufserfahrung ist erwünscht, aber nicht zwingend erforderlich.',options:['Flexible working time','A company car','No previous education']}),Q('read-argument','reading','choice','Why does the writer support the measure?','It reduces traffic and noise',{passage:'Ich unterstütze die neue Fahrradstraße, weil dadurch weniger Autos im Zentrum fahren. Das reduziert Verkehr und Lärm.',options:['It reduces traffic and noise','It creates parking spaces','It lowers ticket prices']}),
      Q('produce-contrast','production','tokens','Build: Although it was raining, we went for a walk.','Obwohl es regnete, gingen wir spazieren.',{tokens:['Obwohl','es regnete,','gingen wir','spazieren.']}),Q('produce-formal','production','input','Complete the formal request: Könnten Sie mir bitte ___, wann der Kurs beginnt?','mitteilen',{answers:['mitteilen']})]
  };
  const page=new URL(location.href),level=['A1','A2','B1'].includes(page.searchParams.get('level'))?page.searchParams.get('level'):'A1',items=sets[level],els={domain:domainLabel,count:countLabel,bar:progressBar,passage,question,answers,feedback,next,result};
  levelPill.textContent=`${level} CHECKPOINT`;title.innerHTML=`${level} readiness<br><em>checkpoint.</em>`;intro.textContent=`Use what you know across five skills. A certificate unlocks only when ${level} evidence is broad and reliable.`;document.querySelectorAll('.level-switch a').forEach(a=>a.classList.toggle('active',a.textContent===level));document.title=`${level} checkpoint — Fallweise`;
  let index=0,results=[],locked=false,started=performance.now(),checkpointStarted=new Date().toISOString(),api=null;const ready=()=>new Promise(resolve=>{if(window.FallweiseProgress)resolve(window.FallweiseProgress);else addEventListener('fallweise:ready',e=>resolve(e.detail),{once:true})});ready().then(x=>api=x);const norm=v=>String(v).trim().toLocaleLowerCase('de-DE').replace(/[.,!?]/g,'').replace(/\s+/g,' ');
  function render(){const q=items[index];locked=false;started=performance.now();els.domain.textContent=q.domain;els.count.textContent=`${index+1} of ${items.length}`;els.bar.style.width=`${(index+1)/items.length*100}%`;els.question.textContent=q.prompt;els.passage.textContent=q.passage||'';els.passage.classList.toggle('show',Boolean(q.passage));els.answers.innerHTML='';els.feedback.textContent='';els.next.style.display='none';if(q.type==='listen')els.answers.insertAdjacentHTML('beforeend',`<div class="placement-audio"><div class="german"><span class="audio-text">${q.audio}</span></div></div>`);if(q.options)q.options.forEach(o=>{const b=document.createElement('button');b.className='answer';b.textContent=o;b.onclick=()=>submit(norm(o)===norm(q.correct),b,o);els.answers.appendChild(b)});else if(q.type==='tokens'){const drop=document.createElement('div'),bank=document.createElement('div'),check=document.createElement('button');drop.className='token-drop';bank.className='token-bank';check.className='check';check.textContent='Check sentence';q.tokens.slice().sort(()=>Math.random()-.5).forEach(t=>{const b=document.createElement('button');b.className='token';b.textContent=t;b.onclick=()=>{(b.parentElement===bank?drop:bank).appendChild(b)};bank.appendChild(b)});check.onclick=()=>{const v=[...drop.children].map(x=>x.textContent).join(' ');submit(norm(v)===norm(q.correct),check,v)};els.answers.append(drop,bank,check)}else{const f=document.createElement('form');f.className='placement-form';f.innerHTML='<input aria-label="Your answer" autocomplete="off" required><button class="check">Check</button>';f.onsubmit=e=>{e.preventDefault();const v=f.querySelector('input').value;submit(q.answers.some(a=>norm(a)===norm(v)),f.querySelector('input'),v)};els.answers.appendChild(f)}}
  async function submit(correct,target,selected){if(locked)return;locked=true;const q=items[index],response_ms=Math.round(performance.now()-started);target.classList.add(correct?'correct':'wrong');if(q.options)[...els.answers.querySelectorAll('.answer')].find(b=>norm(b.textContent)===norm(q.correct))?.classList.add('correct');els.feedback.textContent=correct?'Richtig — this skill is holding.':`Not yet. The useful answer is “${q.correct}”.`;results.push({...q,correct,response_ms});els.next.style.display='inline-block';els.next.disabled=true;api=api||await ready();await api.recordAttempt({exercise_id:`checkpoint:${level}:${q.id}`,skill_id:`checkpoint-${level.toLowerCase()}:${q.domain}`,lesson_id:`checkpoint:${level}`,exercise_type:q.type==='tokens'?'sentence_builder':q.type==='listen'?'listening':q.type==='input'?'fill_blank':'choice',answer:{selected,prompt:q.prompt},correct,hints_used:0,response_ms,attempted_at:new Date().toISOString()});els.next.disabled=false}
  function recommendations(rows){const routes={A1:{vocabulary:'vocabulary.html?set=Home',grammar:'cases.html?level=a1',listening:'skills.html?id=a1-sounds',reading:'skills.html?id=a1-life',production:'lessons.html?id=word-order'},A2:{vocabulary:'vocabulary.html?set=Travel',grammar:'lessons.html?id=connectors',listening:'skills.html?id=a2-life',reading:'skills.html?id=a2-life',production:'skills.html?id=a2-questions'},B1:{vocabulary:'skills.html?id=b1-exam',grammar:'skills.html?id=b1-clauses',listening:'skills.html?id=b1-exam',reading:'lessons.html?id=arguments',production:'skills.html?id=b1-passive-links'}};return routes[level][rows[0].domain]}
  async function finish(){const now=new Date().toISOString(),domains=['vocabulary','grammar','listening','reading','production'].map(domain=>{const r=results.filter(x=>x.domain===domain),correct=r.filter(x=>x.correct).length;return{domain,correct,total:r.length,rate:correct/r.length}}),correct=results.filter(x=>x.correct).length,rate=correct/results.length,passed=rate>=.8&&domains.every(x=>x.rate>=.5),weak=domains.slice().sort((a,b)=>a.rate-b.rate);api=api||await ready();await Promise.all([api.saveLesson({lesson_id:`checkpoint:${level}`,status:'completed',mastery:rate,current_step:10,total_steps:10,started_at:checkpointStarted,completed_at:now,last_activity_at:now}),...domains.map(x=>api.saveSkill({skill_id:`checkpoint-${level.toLowerCase()}:${x.domain}`,level,domain:x.domain==='production'?'writing':x.domain,mastery:x.rate,attempts:x.total,correct_attempts:x.correct,current_streak:0,last_practised_at:now}))]);await api.flush();document.querySelectorAll('.status-line,.progress,#passage,#question,.answers,.feedback,.next').forEach(x=>x.style.display='none');els.result.classList.add('show');els.result.innerHTML=`<div class="kicker">${passed?'Level demonstrated':'Targeted review recommended'}</div><h2>${correct}/10 · ${passed?'Ready':'Nearly there'}</h2><p>${passed?`You demonstrated broad ${level} readiness. Your completion certificate is unlocked.`:`Your strongest evidence is real, but ${weak[0].domain} needs a short focused review before certification.`}</p><div class="gap-list">${domains.map(x=>`<div class="gap"><span>${x.domain}</span><b>${x.correct}/${x.total}</b></div>`).join('')}</div>${passed?`<form class="certificate-form"><input aria-label="Name for certificate" maxlength="60" placeholder="Your name" required><button>Generate certificate</button></form><canvas class="certificate" width="1200" height="675" hidden></canvas><a class="download" hidden download="Fallweise-${level}-certificate.png">Download certificate</a>`:`<a class="retry" href="${recommendations(weak)}">Strengthen ${weak[0].domain} →</a><a class="secondary" href="checkpoint.html?level=${level}">Try checkpoint again</a>`}`;if(passed)installCertificate(correct)}
  function installCertificate(score){const form=els.result.querySelector('form'),canvas=els.result.querySelector('canvas'),download=els.result.querySelector('.download');form.onsubmit=e=>{e.preventDefault();const name=form.querySelector('input').value.trim(),ctx=canvas.getContext('2d'),date=new Date().toLocaleDateString(undefined,{year:'numeric',month:'long',day:'numeric'});ctx.fillStyle='#fffdf6';ctx.fillRect(0,0,1200,675);ctx.strokeStyle='#18201d';ctx.lineWidth=5;ctx.strokeRect(25,25,1150,625);ctx.fillStyle='#254f3d';ctx.fillRect(55,55,1090,12);ctx.fillStyle='#18201d';ctx.textAlign='center';ctx.font='700 42px Georgia';ctx.fillText('fallweise.',600,145);ctx.font='24px Arial';ctx.fillText('CERTIFICATE OF LEVEL COMPLETION',600,205);ctx.font='700 62px Georgia';ctx.fillText(name,600,310);ctx.font='27px Arial';ctx.fillText(`has demonstrated broad German readiness at level ${level}`,600,375);ctx.fillStyle='#254f3d';ctx.font='700 88px Georgia';ctx.fillText(level,600,485);ctx.fillStyle='#18201d';ctx.font='20px Arial';ctx.fillText(`${score}/10 checkpoint evidence · ${date}`,600,570);canvas.hidden=false;download.hidden=false;download.href=canvas.toDataURL('image/png');download.textContent='Download shareable certificate →';canvas.scrollIntoView({behavior:'smooth',block:'center'})}}
  els.next.onclick=()=>{if(index===items.length-1)return finish();index++;render()};render();
})();
