(() => {
  const css=document.createElement('style');css.textContent=`
  body{opacity:0;transition:opacity .4s ease}body.ui-ready{opacity:1}.read-progress{position:fixed;left:0;top:0;height:4px;width:100%;z-index:1000;pointer-events:none}.read-progress i{display:block;height:100%;width:0;background:linear-gradient(90deg,var(--coral,#f1886f),var(--lime,#d9ed72));box-shadow:0 0 12px rgba(217,237,114,.7)}.cursor-glow{position:fixed;width:280px;height:280px;border-radius:50%;left:var(--mx);top:var(--my);transform:translate(-50%,-50%);background:radial-gradient(circle,rgba(217,237,114,.13),transparent 68%);pointer-events:none;z-index:0}.reveal-ui{opacity:0;transform:translateY(24px);transition:opacity .7s ease,transform .7s cubic-bezier(.2,.8,.2,1)}.reveal-ui.visible{opacity:1;transform:none}.tilt-ui{transform-style:preserve-3d;will-change:transform;transition:transform .2s ease,box-shadow .2s}.ripple-ui{position:absolute;border-radius:50%;background:rgba(217,237,114,.45);transform:scale(0);animation:ripple .65s ease-out;pointer-events:none;z-index:9}@keyframes ripple{to{transform:scale(4);opacity:0}}.celebrate{position:fixed;z-index:2000;pointer-events:none;font-size:18px;animation:burst 1s ease-out forwards}@keyframes burst{to{transform:translate(var(--dx),var(--dy)) rotate(240deg);opacity:0}}.journey-toast{position:fixed;right:20px;bottom:20px;background:var(--ink,#18201d);color:white;padding:13px 17px;z-index:100;border-left:5px solid var(--lime,#d9ed72);box-shadow:0 10px 30px #0003;font-size:12px;transform:translateY(100px);opacity:0;transition:.4s}.journey-toast.show{transform:none;opacity:1}.lesson-dock{position:fixed;right:20px;bottom:20px;z-index:90}.lesson-dock a{background:var(--ink,#18201d);color:white;text-decoration:none;padding:12px 15px;font-size:12px;font-weight:700;box-shadow:5px 5px 0 var(--lime,#d9ed72)}.completion-dot{display:inline-block;width:7px;height:7px;border-radius:50%;background:var(--lime,#d9ed72);margin-right:6px}.pulse-correct{animation:correctPulse .5s ease}@keyframes correctPulse{50%{transform:scale(1.018);box-shadow:0 0 0 7px rgba(217,237,114,.18)}}@media(max-width:700px){.cursor-glow,.lesson-dock{display:none}.journey-toast{left:15px;right:15px}}@media(prefers-reduced-motion:reduce){*,*:before,*:after{animation-duration:.01ms!important;transition-duration:.01ms!important}.cursor-glow{display:none}.reveal-ui{opacity:1;transform:none}}`;document.head.appendChild(css);
  const bar=document.createElement('div');bar.className='read-progress';bar.innerHTML='<i></i>';document.body.prepend(bar);const progress=()=>{const h=document.documentElement.scrollHeight-innerHeight;bar.firstChild.style.width=(h?scrollY/h*100:0)+'%'};addEventListener('scroll',progress,{passive:true});progress();
  if(matchMedia('(pointer:fine)').matches){const g=document.createElement('div');g.className='cursor-glow';document.body.appendChild(g);addEventListener('pointermove',e=>{document.documentElement.style.setProperty('--mx',e.clientX+'px');document.documentElement.style.setProperty('--my',e.clientY+'px')},{passive:true})}requestAnimationFrame(()=>document.body.classList.add('ui-ready'));
  const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.08,rootMargin:'0px 0px -30px'});document.querySelectorAll('section,article.level,.course,.word,.example,.principle').forEach((el,i)=>{el.classList.add('reveal-ui');el.style.transitionDelay=(i%4*50)+'ms';io.observe(el)});
  if(matchMedia('(pointer:fine)').matches&&!matchMedia('(prefers-reduced-motion:reduce)').matches)document.querySelectorAll('.course,.lesson.ready,.word,.quiz-card,.quizcard,.hero-card,.tense-card').forEach(el=>{el.classList.add('tilt-ui');el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;el.style.transform=`perspective(800px) rotateX(${-y*3}deg) rotateY(${x*4}deg) translateY(-2px)`});el.addEventListener('pointerleave',()=>el.style.transform='')});
  document.addEventListener('click',e=>{const t=e.target.closest('button,a.lesson,a.course,.word');if(!t)return;const r=t.getBoundingClientRect(),d=Math.max(r.width,r.height),s=document.createElement('span');s.className='ripple-ui';s.style.cssText=`width:${d}px;height:${d}px;left:${e.clientX-r.left-d/2}px;top:${e.clientY-r.top-d/2}px`;if(getComputedStyle(t).position==='static')t.style.position='relative';t.style.overflow='hidden';t.appendChild(s);setTimeout(()=>s.remove(),700)});
  const burst=el=>{if(matchMedia('(prefers-reduced-motion:reduce)').matches)return;const r=el.getBoundingClientRect();for(let i=0;i<18;i++){const p=document.createElement('span'),a=Math.PI*2*i/18,d=55+Math.random()*90;p.className='celebrate';p.textContent=['✦','●','◆'][i%3];p.style.cssText=`left:${r.left+r.width/2}px;top:${r.top+r.height/2}px;color:${['#d9ed72','#f1886f','#8dc8d8'][i%3]};--dx:${Math.cos(a)*d}px;--dy:${Math.sin(a)*d}px`;document.body.appendChild(p);setTimeout(()=>p.remove(),1100)}};
  const f=document.querySelector('#feedback');if(f)new MutationObserver(()=>{if(/Richtig|correct/i.test(f.textContent)){const c=f.closest('.quiz-card,.quizcard')||f;c.classList.remove('pulse-correct');void c.offsetWidth;c.classList.add('pulse-correct');burst(f)}}).observe(f,{childList:true,subtree:true});
  const ids=['word-order','modals','prepositions','connectors','describe','rich-clauses','perspective','arguments'],current=new URLSearchParams(location.search).get('id');const toast=m=>{let t=document.createElement('div');t.className='journey-toast';t.textContent=m;document.body.appendChild(t);requestAnimationFrame(()=>t.classList.add('show'));setTimeout(()=>{t.classList.remove('show');setTimeout(()=>t.remove(),450)},2500)};
  if(current&&ids.includes(current)){const complete=document.querySelector('#complete');if(complete)new MutationObserver(()=>{if(getComputedStyle(complete).display!=='none'){let done=JSON.parse(localStorage.getItem('fallweise-complete')||'[]');if(!done.includes(current)){done.push(current);localStorage.setItem('fallweise-complete',JSON.stringify(done));toast('Chapter saved to your journey ✓');burst(complete)}}}).observe(complete,{attributes:true});const i=ids.indexOf(current),dock=document.createElement('div');dock.className='lesson-dock';dock.innerHTML=i<ids.length-1?`<a href="lessons.html?id=${ids[i+1]}">Next chapter →</a>`:'<a href="index.html">View journey ✓</a>';document.body.appendChild(dock)}
  if(location.pathname.endsWith('/')||location.pathname.endsWith('index.html')){const done=JSON.parse(localStorage.getItem('fallweise-complete')||'[]'),status=document.querySelector('.status');if(status&&done.length)status.innerHTML=`<i class="completion-dot"></i>${done.length} chapter${done.length===1?'':'s'} completed`;document.querySelectorAll('a[href^="lessons.html?id="]').forEach(a=>{const id=new URL(a.href).searchParams.get('id');if(done.includes(id)){const l=a.querySelector('.ready-label');if(l)l.textContent='COMPLETE ✓'}})}
})();
