(() => {
  const SUPABASE_URL='https://xysuwcwgcbbnbpmfdwor.supabase.co';
  const SUPABASE_PUBLISHABLE_KEY='sb_publishable_IDqV0lx_vx3OYR3RrJsA9g_rwuRDVV0';
  const DB_NAME='fallweise-learning';
  const QUEUE_STORE='sync_queue';
  const STATE_STORE='local_state';
  const page=new URL(location.href);
  const lessonId=(()=>{const file=page.pathname.split('/').pop()||'index.html',key=page.searchParams.get('id')||page.searchParams.get('level')||page.searchParams.get('set')||page.searchParams.get('tense');return key?`${file.replace('.html','')}:${key}`:file.replace('.html','')})();
  const level=(document.querySelector('[id$="Pill"],.progress-pill,.pill')?.textContent.match(/\b(A1|A2|B1)\b/)||document.title.match(/\b(A1|A2|B1)\b/)||[])[1]||null;
  let client=null,user=null,flushing=false;

  const css=document.createElement('style');css.textContent=`.cloud-sync{position:fixed;right:14px;bottom:14px;z-index:89;border:1px solid var(--line,#d8d4c8);background:var(--paper,#fffdf6);color:var(--muted,#66706b);padding:6px 9px;border-radius:99px;font:600 10px/1.2 'DM Sans',sans-serif;box-shadow:0 5px 16px #0001;transition:.2s}.cloud-sync[data-state=ready]{color:var(--green,#254f3d)}.cloud-sync[data-state=offline]{color:#8b5e34}@media(max-width:700px){.cloud-sync{right:8px;bottom:max(8px,env(safe-area-inset-bottom));font-size:9px;padding:5px 7px}}`;
  document.head.appendChild(css);
  const badge=document.createElement('div');badge.className='cloud-sync';badge.setAttribute('role','status');badge.setAttribute('aria-live','polite');badge.dataset.state='loading';badge.textContent='Saving progress…';document.body.appendChild(badge);
  const setStatus=(state,text)=>{badge.dataset.state=state;badge.textContent=text};

  function openDb(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,1);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains(QUEUE_STORE))db.createObjectStore(QUEUE_STORE,{keyPath:'id',autoIncrement:true});if(!db.objectStoreNames.contains(STATE_STORE))db.createObjectStore(STATE_STORE,{keyPath:'key'})};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
  async function dbRequest(store,mode,work){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(store,mode),os=tx.objectStore(store),req=work(os);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);tx.oncomplete=()=>db.close()})}
  const queue=payload=>dbRequest(QUEUE_STORE,'readwrite',s=>s.add({payload,createdAt:new Date().toISOString()}));
  const queued=()=>dbRequest(QUEUE_STORE,'readonly',s=>s.getAll());
  const removeQueued=id=>dbRequest(QUEUE_STORE,'readwrite',s=>s.delete(id));
  const saveLocal=(key,value)=>dbRequest(STATE_STORE,'readwrite',s=>s.put({key,value,updatedAt:new Date().toISOString()}));

  async function send(item){if(!client||!user)throw new Error('Cloud unavailable');const p=item.payload;if(p.kind==='attempt'){const {error}=await client.from('exercise_attempts').insert({...p.row,user_id:user.id});if(error)throw error}else if(p.kind==='progress'){const {error}=await client.from('lesson_progress').upsert({...p.row,user_id:user.id},{onConflict:'user_id,lesson_id'});if(error)throw error}else if(p.kind==='settings'){const {error}=await client.from('user_settings').update(p.row).eq('user_id',user.id);if(error)throw error}}
  async function flush(){if(flushing||!client||!user||!navigator.onLine)return;flushing=true;try{const items=await queued();for(const item of items){await send(item);await removeQueued(item.id)}setStatus('ready','Progress saved')}catch(error){console.warn('Fallweise sync deferred:',error.message);setStatus('offline','Saved on this device')}finally{flushing=false}}
  async function persist(payload){await queue(payload);await saveLocal('last_activity',{lessonId,at:new Date().toISOString()});setStatus(navigator.onLine?'loading':'offline',navigator.onLine?'Saving progress…':'Saved on this device');flush()}
  const slug=s=>String(s||'item').toLowerCase().normalize('NFKD').replace(/[^a-z0-9äöüß]+/gi,'-').replace(/^-|-$/g,'').slice(0,70)||'item';
  const answerResults=new Map();
  function recordAnswer(button){const box=button.closest('.quiz-card,.quizcard,.practice,.quiz,.check')||button.parentElement?.parentElement;if(!box)return;const countText=box.querySelector('#qcount,#quizCount,#count')?.textContent||'',numbers=countText.match(/\d+/g)||[],step=Number(numbers[0]||1),total=Number(numbers[1]||step),trackingKey=`${lessonId}:${step}`;if(box.dataset.progressRecorded===trackingKey)return;box.dataset.progressRecorded=trackingKey;queueMicrotask(()=>{const prompt=box.querySelector('#question,#quizQ,.question:not(.answer),.quiz-q')?.textContent.trim()||'Question',correct=button.classList.contains('correct')&&!button.classList.contains('wrong'),now=new Date().toISOString();answerResults.set(step,correct);const correctCount=[...answerResults.values()].filter(Boolean).length,mastery=Math.min(.9,Math.max(.08,correctCount/Math.max(total,1))),finished=step>=total,row={exercise_id:`${lessonId}:q${step}:${slug(prompt)}`,skill_id:lessonId,lesson_id:lessonId,exercise_type:'choice',answer:{selected:button.textContent.trim(),prompt},correct,hints_used:0,attempted_at:now},progress={lesson_id:lessonId,status:finished?'completed':'in_progress',mastery,current_step:step,total_steps:total,last_activity_at:now};if(step===1)progress.started_at=now;if(finished)progress.completed_at=now;persist({kind:'attempt',row});persist({kind:'progress',row:progress})})}
  document.addEventListener('click',event=>{const answer=event.target.closest('.answer');if(answer)recordAnswer(answer)});
  document.addEventListener('change',event=>{if(event.target.id==='speechRate'){const speech_rate=Number(event.target.value);saveLocal('speech_rate',speech_rate);persist({kind:'settings',row:{speech_rate}})}});
  const complete=document.querySelector('#complete');if(complete)new MutationObserver(()=>{if(getComputedStyle(complete).display!=='none'){const now=new Date().toISOString(),total=answerResults.size||1,correct=[...answerResults.values()].filter(Boolean).length;persist({kind:'progress',row:{lesson_id:lessonId,status:'completed',mastery:Math.min(.9,Math.max(.08,correct/total)),current_step:total,total_steps:total,completed_at:now,last_activity_at:now}})}}).observe(complete,{attributes:true,childList:true});

  async function init(){try{const {createClient}=await import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm');client=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});let {data:{session}}=await client.auth.getSession();if(!session){const {data,error}=await client.auth.signInAnonymously();if(error)throw error;session=data.session}user=session.user;window.FallweiseProgress={client,user,lessonId,flush,recordAttempt:row=>persist({kind:'attempt',row}),saveLesson:row=>persist({kind:'progress',row})};await flush();setStatus('ready','Progress saved')}catch(error){console.warn('Fallweise cloud unavailable:',error.message);window.FallweiseProgress={client:null,user:null,lessonId,flush:()=>Promise.resolve(),recordAttempt:row=>persist({kind:'attempt',row}),saveLesson:row=>persist({kind:'progress',row})};setStatus('offline','Saved on this device')}}
  addEventListener('online',flush);init();
})();
