(() => {
  const SUPABASE_URL='https://xysuwcwgcbbnbpmfdwor.supabase.co';
  const SUPABASE_PUBLISHABLE_KEY='sb_publishable_IDqV0lx_vx3OYR3RrJsA9g_rwuRDVV0';
  const DB_NAME='fallweise-learning';
  const QUEUE_STORE='sync_queue';
  const STATE_STORE='local_state';
  const TRANSFER_KEY='fallweise-account-transfer';
  const page=new URL(location.href);
  const lessonId=(()=>{const file=page.pathname.split('/').pop()||'index.html',key=page.searchParams.get('id')||page.searchParams.get('level')||page.searchParams.get('set')||page.searchParams.get('tense');return key?`${file.replace('.html','')}:${key}`:file.replace('.html','')})();
  const level=(document.querySelector('[id$="Pill"],.progress-pill,.pill')?.textContent.match(/\b(A1|A2|B1)\b/)||document.title.match(/\b(A1|A2|B1)\b/)||[])[1]||null;
  let client=null,user=null,flushPromise=null;

  const css=document.createElement('style');css.textContent=`.cloud-sync{position:fixed;right:14px;bottom:14px;z-index:89;border:1px solid var(--line,#d8d4c8);background:var(--paper,#fffdf6);color:var(--muted,#66706b);padding:6px 9px;border-radius:99px;font:600 10px/1.2 'DM Sans',sans-serif;box-shadow:0 5px 16px #0001;transition:.2s}.cloud-sync[data-state=ready]{color:var(--green,#254f3d)}.cloud-sync[data-state=offline]{color:#8b5e34}.account-button{border:1px solid currentColor;background:transparent;color:inherit;border-radius:99px;padding:8px 12px;font:700 11px 'DM Sans',sans-serif;cursor:pointer}.account-dialog{border:0;padding:0;background:transparent;color:var(--ink,#18201d);max-width:min(440px,calc(100vw - 28px));width:100%}.account-dialog::backdrop{background:#18201dcc;backdrop-filter:blur(4px)}.account-card{position:relative;background:var(--paper,#fffdf6);border:1px solid var(--ink,#18201d);box-shadow:9px 9px 0 var(--lime,#d9ed72);padding:30px}.account-card h2{font:700 32px/1.05 'Fraunces',serif;margin:8px 35px 12px 0}.account-card p{color:var(--muted,#66706b);font-size:14px;line-height:1.55}.account-card form{display:flex;gap:8px;margin-top:20px}.account-card input{min-width:0;flex:1;border:1px solid var(--line,#d8d4c8);background:white;padding:12px;font:inherit}.account-card form button{border:0;background:var(--green,#254f3d);color:white;padding:12px 15px;font-weight:700;cursor:pointer}.account-close{position:absolute;right:14px;top:12px;border:0;background:none;font-size:25px;cursor:pointer}.account-message{min-height:20px;font-weight:700}.lesson[data-progress=completed]{border-color:var(--lime,#d9ed72);box-shadow:inset 5px 0 0 var(--lime,#d9ed72)}.lesson[data-progress=in_progress]{border-color:var(--blue,#8dc8d8);box-shadow:inset 5px 0 0 var(--blue,#8dc8d8)}.resume-note{display:block;margin-top:8px;font-size:11px;font-weight:700;color:var(--green,#254f3d)}@media(max-width:700px){.cloud-sync{right:8px;bottom:max(8px,env(safe-area-inset-bottom));font-size:9px;padding:5px 7px}.account-button{padding:7px 9px;font-size:10px}.account-card form{flex-direction:column}}`;
  document.head.appendChild(css);
  const badge=document.createElement('div');badge.className='cloud-sync';badge.setAttribute('role','status');badge.setAttribute('aria-live','polite');badge.dataset.state='loading';badge.textContent='Saving progress…';document.body.appendChild(badge);
  const setStatus=(state,text)=>{badge.dataset.state=state;badge.textContent=text};

  function openDb(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,1);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains(QUEUE_STORE))db.createObjectStore(QUEUE_STORE,{keyPath:'id',autoIncrement:true});if(!db.objectStoreNames.contains(STATE_STORE))db.createObjectStore(STATE_STORE,{keyPath:'key'})};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
  async function dbRequest(store,mode,work){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(store,mode),os=tx.objectStore(store),req=work(os);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);tx.oncomplete=()=>db.close()})}
  const queue=payload=>dbRequest(QUEUE_STORE,'readwrite',s=>s.add({payload,createdAt:new Date().toISOString()}));
  const queued=()=>dbRequest(QUEUE_STORE,'readonly',s=>s.getAll());
  const removeQueued=id=>dbRequest(QUEUE_STORE,'readwrite',s=>s.delete(id));
  const saveLocal=(key,value)=>dbRequest(STATE_STORE,'readwrite',s=>s.put({key,value,updatedAt:new Date().toISOString()}));

  function accountUi(){
    const nav=document.querySelector('nav');if(!nav)return;
    const button=document.createElement('button');button.className='account-button';button.type='button';button.textContent=user?.is_anonymous?'Save progress':'Account';
    const dialog=document.createElement('dialog');dialog.className='account-dialog';dialog.innerHTML=`<div class="account-card"><button class="account-close" type="button" aria-label="Close">×</button><div class="kicker">Your learning account</div><h2>${user?.is_anonymous?'Keep every win.':'Progress protected.'}</h2><p>${user?.is_anonymous?'Add your email to resume after clearing browser data, using a private window, or changing devices. Your current progress stays with you.':`Signed in as <b>${user?.email||'learner'}</b>. Your progress can follow you across browsers and devices.`}</p>${user?.is_anonymous?'<form><input type="email" autocomplete="email" placeholder="you@example.com" aria-label="Email address" required><button type="submit">Email me a link</button></form>':''}<p class="account-message" role="status"></p></div>`;
    const oldStatus=nav.querySelector('.status');if(oldStatus)nav.insertBefore(button,oldStatus);else nav.appendChild(button);document.body.appendChild(dialog);button.onclick=()=>dialog.showModal();dialog.querySelector('.account-close').onclick=()=>dialog.close();dialog.onclick=e=>{if(e.target===dialog)dialog.close()};
    dialog.querySelector('form')?.addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,email=form.querySelector('input').value.trim(),message=dialog.querySelector('.account-message'),submit=form.querySelector('button');submit.disabled=true;message.textContent='Preparing your account…';try{await exportForTransfer();const redirectTo=new URL('index.html?account=confirmed',location.href).href;const {error}=await client.auth.updateUser({email},{emailRedirectTo:redirectTo});if(error){const otp=await client.auth.signInWithOtp({email,options:{shouldCreateUser:false,emailRedirectTo:redirectTo}});if(otp.error)throw otp.error}message.textContent='Check your inbox and open the secure link on this device.'}catch(error){message.textContent=error.message||'Could not send the link. Please try again.'}finally{submit.disabled=false}});
  }

  async function exportForTransfer(){
    if(!client||!user)return;const tables=['lesson_progress','exercise_attempts','skill_mastery','review_items'];const snapshot={userId:user.id,createdAt:new Date().toISOString(),tables:{}};
    for(const table of tables){const {data,error}=await client.from(table).select('*');if(error)throw error;snapshot.tables[table]=data||[]}
    localStorage.setItem(TRANSFER_KEY,JSON.stringify(snapshot));
  }
  async function importTransfer(){
    const raw=localStorage.getItem(TRANSFER_KEY);if(!raw||!client||!user)return;let snapshot;try{snapshot=JSON.parse(raw)}catch{return localStorage.removeItem(TRANSFER_KEY)}
    if(snapshot.userId===user.id)return localStorage.removeItem(TRANSFER_KEY);
    const incoming=snapshot.tables?.lesson_progress||[],{data:existing}=await client.from('lesson_progress').select('*');const byId=new Map((existing||[]).map(row=>[row.lesson_id,row]));
    const merged=incoming.map(row=>{const current=byId.get(row.lesson_id),winner=!current||row.status==='completed'&&current.status!=='completed'||Number(row.mastery)>Number(current.mastery)?row:current;return {...winner,user_id:user.id}});
    if(merged.length){const {error}=await client.from('lesson_progress').upsert(merged,{onConflict:'user_id,lesson_id'});if(error)throw error}
    const attempts=(snapshot.tables?.exercise_attempts||[]).map(({id,...row})=>({...row,user_id:user.id}));if(attempts.length){const {error}=await client.from('exercise_attempts').insert(attempts);if(error)throw error}
    for(const table of ['skill_mastery','review_items']){const rows=(snapshot.tables?.[table]||[]).map(row=>({...row,user_id:user.id}));if(rows.length){const conflict=table==='skill_mastery'?'user_id,skill_id':'user_id,item_id',{error}=await client.from(table).upsert(rows,{onConflict:conflict});if(error)throw error}}
    localStorage.removeItem(TRANSFER_KEY);
  }

  const lessonIdForHref=href=>{const url=new URL(href,location.href),file=url.pathname.split('/').pop()?.replace('.html','')||'index',key=url.searchParams.get('id')||url.searchParams.get('level')||url.searchParams.get('set')||url.searchParams.get('tense');return key?`${file}:${key}`:file};
  async function decorateCourse(){
    if(!location.pathname.endsWith('/')&&!location.pathname.endsWith('index.html'))return;const {data,error}=await client.from('lesson_progress').select('*').order('last_activity_at',{ascending:false});if(error)return;const rows=data||[],byId=new Map(rows.map(row=>[row.lesson_id,row]));
    document.querySelectorAll('a.lesson').forEach(link=>{const row=byId.get(lessonIdForHref(link.href));if(!row)return;link.dataset.progress=row.status;const label=link.querySelector('.ready-label');if(label)label.textContent=row.status==='completed'?'✓ DONE':`STEP ${Math.min(row.current_step+1,row.total_steps||1)} OF ${row.total_steps||1}`});
    const latest=rows.find(row=>row.status==='in_progress')||rows[0];if(latest){const link=[...document.querySelectorAll('a.lesson')].find(a=>lessonIdForHref(a.href)===latest.lesson_id);if(link){const start=document.querySelector('.start'),resume=new URL(link.href);if(latest.status==='in_progress')resume.searchParams.set('resume',String(Math.min(latest.current_step+1,latest.total_steps||latest.current_step+1)));start.href=resume.href;start.textContent=latest.status==='completed'?'Review your last lesson →':'Continue learning →';const note=document.createElement('span');note.className='resume-note';note.textContent=latest.status==='completed'?'Last lesson completed':`Resume at step ${Math.min(latest.current_step+1,latest.total_steps||latest.current_step+1)}`;start.after(note)}}
    const completed=rows.filter(row=>row.status==='completed').length,inProgress=rows.filter(row=>row.status==='in_progress').length,status=document.querySelector('nav .status');if(status)status.textContent=`${completed} completed · ${inProgress} in progress`;
    await renderDailyReview();
  }
  async function renderDailyReview(){const path=document.querySelector('.path');if(!path)return;const {data,error}=await client.rpc('get_daily_review',{requested_limit:6});if(error)return;const due=data||[],section=document.createElement('section');section.className='daily-review';section.innerHTML=`<div class="inner"><div><div class="kicker">Spaced review</div><h2>${due.length?`${due.length} memories ready today.`:'Your memory queue is clear.'}</h2><p>${due.length?'Short retrieval now keeps these patterns available later.':'Complete lessons and difficult items will return here at the right time.'}</p></div><div class="review-list">${due.length?due.map(item=>`<a href="${reviewHref(item)}" class="review-card"><span>${item.item_type.replace('_',' ')}</span><b>${reviewTitle(item.item_id)}</b><small>Review now →</small></a>`).join(''):'<div class="review-empty">Nothing due yet · Weiter so!</div>'}</div></div>`;path.after(section);const style=document.createElement('style');style.textContent=`.daily-review{padding:72px 24px;background:var(--paper,#fffdf6)}.daily-review>.inner{display:grid;grid-template-columns:.75fr 1.25fr;gap:55px}.daily-review h2{font:700 clamp(36px,5vw,58px)/1 'Fraunces';margin:10px 0}.daily-review p{color:var(--muted);line-height:1.55}.review-list{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.review-card,.review-empty{border:1px solid var(--line);padding:18px;text-decoration:none;background:white;min-height:120px;display:flex;flex-direction:column}.review-card span{font-size:10px;text-transform:uppercase;letter-spacing:.12em;color:var(--muted)}.review-card b{font:600 18px 'Fraunces';margin:12px 0}.review-card small{margin-top:auto;color:var(--green);font-weight:700}@media(max-width:700px){.daily-review>.inner{grid-template-columns:1fr}.review-list{grid-template-columns:1fr}}`;document.head.appendChild(style)}
  const reviewTitle=id=>{const parts=id.split(':');if(parts[0]==='vocab')return `${parts[2]} · ${parts[3]}`;if(parts[0]==='syntax')return `${parts[1].replace(/-/g,' ')} · ${parts[2].replace(/-/g,' ')}`;if(parts[0]==='lab')return `${parts[1].replace('a1-','').replace(/-/g,' ')} · ${parts[2].replace(/-/g,' ')}`;return parts.pop().replace(/-/g,' ').replace(/^./,c=>c.toUpperCase())};
  const reviewHref=item=>{if(item.skill_id.includes('-cases:'))return `cases.html?level=${item.skill_id.split('-')[0]}&review=${encodeURIComponent(item.item_id)}`;if(item.item_id.startsWith('vocab:')){const parts=item.item_id.split(':'),match=parts[1].match(/^(A1|A2|B1)-(.+)$/);if(match)return `vocabulary-path.html?level=${match[1]}&unit=${encodeURIComponent(match[2])}&review=${encodeURIComponent(item.item_id)}`;return `vocabulary.html?set=${encodeURIComponent(parts[1])}&review=${encodeURIComponent(item.item_id)}`}if(item.item_id.startsWith('syntax:')){const lesson=item.item_id.split(':')[1],base=lesson==='present'?'course.html?tense=0':`lessons.html?id=${lesson}`;return `${base}&review=${encodeURIComponent(item.item_id)}`}if(item.item_id.startsWith('lab:'))return `skills.html?id=${item.item_id.split(':')[1]}&review=${encodeURIComponent(item.item_id)}`;return 'index.html'};
  function resumeLesson(){const requested=Number(page.searchParams.get('resume')||1),next=document.querySelector('#next');if(!next||requested<2||next.closest('[data-adaptive=true]'))return;for(let step=1;step<requested;step++)next.click();next.scrollIntoView({behavior:'smooth',block:'center'})}

  async function send(item){if(!client||!user)throw new Error('Cloud unavailable');const p=item.payload;if(p.kind==='attempt'){const row={...p.row,exercise_type:p.row.exercise_type==='voice'?'speaking':p.row.exercise_type,user_id:user.id},{error}=await client.from('exercise_attempts').insert(row);if(error)throw error}else if(p.kind==='progress'){const {error}=await client.from('lesson_progress').upsert({...p.row,user_id:user.id},{onConflict:'user_id,lesson_id'});if(error)throw error}else if(p.kind==='skill'){const {error}=await client.from('skill_mastery').upsert({...p.row,user_id:user.id},{onConflict:'user_id,skill_id'});if(error)throw error}else if(p.kind==='review'){const {error}=await client.from('review_items').upsert({...p.row,user_id:user.id},{onConflict:'user_id,item_id'});if(error)throw error}else if(p.kind==='settings'){const {error}=await client.from('user_settings').update(p.row).eq('user_id',user.id);if(error)throw error}}
  function flush(){if(flushPromise)return flushPromise;if(!client||!user||!navigator.onLine)return Promise.resolve();flushPromise=(async()=>{try{let items;do{items=await queued();for(const item of items){await send(item);await removeQueued(item.id)}}while(items.length);setStatus('ready','Progress saved')}catch(error){console.warn('Fallweise sync deferred:',error.message);setStatus('offline','Saved on this device')}finally{flushPromise=null}})();return flushPromise}
  async function persist(payload){await queue(payload);await saveLocal('last_activity',{lessonId,at:new Date().toISOString()});setStatus(navigator.onLine?'loading':'offline',navigator.onLine?'Saving progress…':'Saved on this device');return flush()}
  const slug=s=>String(s||'item').toLowerCase().normalize('NFKD').replace(/[^a-z0-9äöüß]+/gi,'-').replace(/^-|-$/g,'').slice(0,70)||'item';
  const answerResults=new Map();
  function recordAnswer(button){const box=button.closest('.quiz-card,.quizcard,.practice,.quiz,.check')||button.parentElement?.parentElement;if(!box||box.dataset.adaptive==='true')return;const countText=box.querySelector('#qcount,#quizCount,#count')?.textContent||'',numbers=countText.match(/\d+/g)||[],step=Number(numbers[0]||1),total=Number(numbers[1]||step),trackingKey=`${lessonId}:${step}`;if(box.dataset.progressRecorded===trackingKey)return;box.dataset.progressRecorded=trackingKey;queueMicrotask(()=>{const prompt=box.querySelector('#question,#quizQ,.question:not(.answer),.quiz-q')?.textContent.trim()||'Question',correct=button.classList.contains('correct')&&!button.classList.contains('wrong'),now=new Date().toISOString();answerResults.set(step,correct);const correctCount=[...answerResults.values()].filter(Boolean).length,mastery=Math.min(.9,Math.max(.08,correctCount/Math.max(total,1))),finished=step>=total,row={exercise_id:`${lessonId}:q${step}:${slug(prompt)}`,skill_id:lessonId,lesson_id:lessonId,exercise_type:'choice',answer:{selected:button.textContent.trim(),prompt},correct,hints_used:0,attempted_at:now},progress={lesson_id:lessonId,status:finished?'completed':'in_progress',mastery,current_step:step,total_steps:total,last_activity_at:now};if(step===1)progress.started_at=now;if(finished)progress.completed_at=now;persist({kind:'attempt',row});persist({kind:'progress',row:progress})})}
  document.addEventListener('click',event=>{const answer=event.target.closest('.answer');if(answer)recordAnswer(answer)});
  document.addEventListener('change',event=>{if(event.target.id==='speechRate'){const speech_rate=Number(event.target.value);saveLocal('speech_rate',speech_rate);persist({kind:'settings',row:{speech_rate}})}});
  const complete=document.querySelector('#complete');if(complete)new MutationObserver(()=>{if(getComputedStyle(complete).display!=='none'){const now=new Date().toISOString(),total=answerResults.size||1,correct=[...answerResults.values()].filter(Boolean).length;persist({kind:'progress',row:{lesson_id:lessonId,status:'completed',mastery:Math.min(.9,Math.max(.08,correct/total)),current_step:total,total_steps:total,completed_at:now,last_activity_at:now}})}}).observe(complete,{attributes:true,childList:true});

  async function init(){try{const {createClient}=await import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm');client=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});let {data:{session}}=await client.auth.getSession();if(!session){const {data,error}=await client.auth.signInAnonymously();if(error)throw error;session=data.session}user=session.user;window.FallweiseProgress={client,user,lessonId,flush,recordAttempt:row=>persist({kind:'attempt',row}),saveLesson:row=>persist({kind:'progress',row}),saveSkill:row=>persist({kind:'skill',row}),saveReview:row=>persist({kind:'review',row})};dispatchEvent(new CustomEvent('fallweise:ready',{detail:window.FallweiseProgress}));await importTransfer();await flush();accountUi();await decorateCourse();resumeLesson();if(page.searchParams.get('account')==='confirmed'&&!user.is_anonymous){history.replaceState({},'',new URL('index.html',location.href));setStatus('ready','Account connected · progress saved')}else setStatus('ready','Progress saved')}catch(error){console.warn('Fallweise cloud unavailable:',error.message);window.FallweiseProgress={client:null,user:null,lessonId,flush:()=>Promise.resolve(),recordAttempt:row=>persist({kind:'attempt',row}),saveLesson:row=>persist({kind:'progress',row}),saveSkill:row=>persist({kind:'skill',row}),saveReview:row=>persist({kind:'review',row})};dispatchEvent(new CustomEvent('fallweise:ready',{detail:window.FallweiseProgress}));setStatus('offline','Saved on this device')}}
  addEventListener('online',flush);init();
})();
