(() => {
  const Q=(id,level,domain,type,prompt,correct,extra={})=>({id,level,domain,type,prompt,correct,...extra});
  const questions=[
    Q('a1-vocab','A1','vocabulary','choice','What does “der Bahnhof” mean?','train station',{options:['train station','town hall','supermarket']}),
    Q('a1-grammar','A1','grammar','choice','Complete: Ich ___ in Berlin.','wohne',{options:['wohne','wohnt','wohnst']}),
    Q('a1-listen','A1','listening','listen','What information does the speaker want?','the price',{audio:'Wie viel kostet das Brot?',options:['the price','the time','the address']}),
    Q('a1-sentence','A1','sentence','tokens','Build: Tomorrow I am travelling to Cologne.','Morgen fahre ich nach Köln.',{tokens:['Morgen','fahre','ich','nach Köln.']}),
    Q('a2-vocab','A2','vocabulary','choice','What does “einen Termin verschieben” mean?','reschedule an appointment',{options:['cancel a journey','reschedule an appointment','confirm an address']}),
    Q('a2-grammar','A2','grammar','choice','Choose the correct clause.','weil ich heute arbeiten muss',{options:['weil ich muss heute arbeiten','weil ich heute arbeiten muss','weil muss ich heute arbeiten']}),
    Q('a2-listen','A2','listening','listen','What happened to the train?','It was cancelled.',{audio:'Der Zug fällt heute leider aus.',options:['It was cancelled.','It is delayed.','It changed platforms.']}),
    Q('a2-sentence','A2','sentence','tokens','Build: I have already booked the hotel.','Ich habe das Hotel schon gebucht.',{tokens:['Ich','habe','das Hotel','schon','gebucht.']}),
    Q('b1-vocab','B1','vocabulary','choice','Which is the natural collocation?','Verantwortung übernehmen',{options:['Verantwortung machen','Verantwortung übernehmen','Verantwortung bekommen']}),
    Q('b1-grammar','B1','grammar','choice','Die Frau, ___ ich helfe, ist meine Nachbarin.','der',{options:['die','der','deren']}),
    Q('b1-listen','B1','listening','listen','What relationship does the sentence express?','contrast',{audio:'Obwohl die Wohnung klein ist, gefällt sie uns sehr.',options:['contrast','cause','sequence']}),
    Q('b1-sentence','B1','sentence','tokens','Build: The application must be submitted by Friday.','Die Bewerbung muss bis Freitag eingereicht werden.',{tokens:['Die Bewerbung','muss','bis Freitag','eingereicht','werden.']})
  ];
  const els={stage:stageLabel,progress:progressLabel,bar:progressBar,domain:domainLabel,question,answers,feedback,next,result};
  let index=0,active=questions.slice(0,4),results=[],locked=false,started=performance.now(),assessmentStarted=new Date().toISOString(),api=null;
  const ready=()=>new Promise(resolve=>{if(window.FallweiseProgress)resolve(window.FallweiseProgress);else addEventListener('fallweise:ready',e=>resolve(e.detail),{once:true})});
  ready().then(value=>api=value);
  const normalize=v=>String(v).trim().toLocaleLowerCase('de-DE').replace(/[.,!?]/g,'').replace(/\s+/g,' ');
  function stageQuestions(level){return questions.filter(q=>q.level===level)}
  function score(level){const rows=results.filter(r=>r.level===level);return rows.filter(r=>r.correct).length}
  function render(){locked=false;started=performance.now();const q=active[index],stageStart=q.level==='A1'?0:q.level==='A2'?4:8;els.stage.textContent=`${q.level} ${q.level==='A1'?'foundations':q.level==='A2'?'everyday range':'independent range'}`;els.progress.textContent=`${index-stageStart+1} of 4`;els.bar.style.width=`${(index+1)/12*100}%`;els.domain.textContent=q.domain;els.question.textContent=q.prompt;els.answers.innerHTML='';els.feedback.textContent='';els.next.style.display='none';if(q.type==='listen')els.answers.insertAdjacentHTML('beforeend',`<div class="placement-audio"><div class="german"><span class="audio-text">${q.audio}</span></div></div>`);if(q.options)q.options.forEach(option=>{const b=document.createElement('button');b.className='answer';b.textContent=option;b.onclick=()=>submit(normalize(option)===normalize(q.correct),b,option);els.answers.appendChild(b)});else if(q.type==='tokens'){const drop=document.createElement('div'),bank=document.createElement('div'),check=document.createElement('button');drop.className='token-drop';bank.className='token-bank';check.className='check';check.textContent='Check sentence';q.tokens.slice().sort(()=>Math.random()-.5).forEach(token=>{const b=document.createElement('button');b.className='token';b.textContent=token;b.onclick=()=>{(b.parentElement===bank?drop:bank).appendChild(b)};bank.appendChild(b)});check.onclick=()=>{const value=[...drop.children].map(x=>x.textContent).join(' ');submit(normalize(value)===normalize(q.correct),check,value)};els.answers.append(drop,bank,check)}}
  async function submit(correct,target,selected){if(locked)return;locked=true;const q=active[index],responseMs=Math.round(performance.now()-started);target.classList.add(correct?'correct':'wrong');if(q.options)[...els.answers.querySelectorAll('.answer')].find(b=>normalize(b.textContent)===normalize(q.correct))?.classList.add('correct');els.feedback.textContent=correct?'Richtig — that evidence is secure.':`Not yet. The answer is “${q.correct}”.`;results.push({...q,correct,responseMs,selected});els.next.style.display='inline-block';els.next.disabled=true;await saveAttempt(q,correct,selected,responseMs);els.next.disabled=false}
  async function saveAttempt(q,correct,selected,response_ms){api=api||await ready();const now=new Date().toISOString();await api.recordAttempt({exercise_id:`placement:${q.id}`,skill_id:`placement:${q.domain}`,lesson_id:'placement:test',exercise_type:q.type==='tokens'?'sentence_builder':q.type==='listen'?'listening':'choice',answer:{selected,prompt:q.prompt,level:q.level},correct,hints_used:0,response_ms,attempted_at:now})}
  function advance(){const q=active[index];if(q.level==='A1'&&index===3){if(score('A1')<3)return finish('A1');active.push(...stageQuestions('A2'))}else if(q.level==='A2'&&index===7){if(score('A2')<3)return finish('A2');active.push(...stageQuestions('B1'))}else if(q.level==='B1'&&index===11)return finish('B1');index++;render()}
  function route(level,weak){const routes={A1:{vocabulary:'vocabulary.html?set=People',grammar:'cases.html?level=a1',listening:'skills.html?id=a1-sounds',sentence:'lessons.html?id=word-order'},A2:{vocabulary:'vocabulary.html?set=Travel',grammar:'cases.html?level=a2',listening:'skills.html?id=a2-life',sentence:'lessons.html?id=connectors'},B1:{vocabulary:'skills.html?id=b1-exam',grammar:'skills.html?id=b1-clauses',listening:'skills.html?id=b1-exam',sentence:'lessons.html?id=arguments'}};return routes[level][weak]}
  async function finish(level){const attempted=results.length,accuracy=results.filter(r=>r.correct).length/attempted,domainRows=['vocabulary','grammar','listening','sentence'].map(domain=>{const rows=results.filter(r=>r.domain===domain);return {domain,correct:rows.filter(r=>r.correct).length,total:rows.length,rate:rows.length?rows.filter(r=>r.correct).length/rows.length:0}}),weak=domainRows.slice().sort((a,b)=>a.rate-b.rate)[0].domain,now=new Date().toISOString();api=api||await ready();await Promise.all([api.saveLesson({lesson_id:'placement:test',status:'completed',mastery:accuracy,current_step:attempted,total_steps:attempted,started_at:assessmentStarted,completed_at:now,last_activity_at:now}),...domainRows.map(row=>api.saveSkill({skill_id:`placement:${row.domain}`,level,domain:row.domain==='sentence'?'grammar':row.domain,mastery:row.rate,attempts:row.total,correct_attempts:row.correct,current_streak:0,last_practised_at:now}))]);if(api.client)await api.client.from('profiles').update({current_level:level}).eq('id',api.user.id);await api.flush();localStorage.setItem('fallweise-placement',JSON.stringify({level,weak,at:now}));document.querySelectorAll('.stage-line,.progress,.domain,#question,.answers,.feedback,.next').forEach(x=>x.style.display='none');els.result.classList.add('show');els.result.innerHTML=`<div class="kicker">Your recommended starting level</div><h2>${level}</h2><p>You showed enough reliable evidence to begin at <b>${level}</b>. Your clearest growth opportunity is <b>${weak}</b>, so your first lesson targets that area. You can still open any level from the course page.</p><div class="result-grid">${domainRows.map(x=>`<div><b>${x.correct}/${x.total}</b><span>${x.domain}</span></div>`).join('')}</div><a href="${route(level,weak)}">Start my recommended lesson →</a><a class="secondary" href="index.html#${level.toLowerCase()}">See the ${level} course</a>`}
  els.next.onclick=advance;render();
})();
