(() => {
  const content={
    A1:[
      {kind:'Listen and repeat',prompt:'Introduce yourself clearly.',de:'Hallo, ich heiße Lina und ich komme aus Spanien.',en:'Hello, my name is Lina and I come from Spain.',chunks:['Hallo,','ich heiße Lina','und ich komme aus Spanien.']},
      {kind:'Shadow the rhythm',prompt:'Ask for something politely.',de:'Ich hätte gern einen Kaffee, bitte.',en:'I would like a coffee, please.',chunks:['Ich hätte gern','einen Kaffee,','bitte.']},
      {kind:'Respond to Vivian',prompt:'Vivian asks: Was machst du gern? Answer with your own hobby.',de:'Ich lese gern und am Wochenende treffe ich Freunde.',en:'I like reading and on weekends I meet friends.',chunks:['Ich lese gern','und am Wochenende','treffe ich Freunde.'],personal:'Write your answer first (optional)'},
      {kind:'Dialogue role',prompt:'You are arranging a meeting. Say when you are free.',de:'Am Dienstag habe ich Zeit. Passt es dir um drei Uhr?',en:'I have time on Tuesday. Does three o’clock suit you?',chunks:['Am Dienstag','habe ich Zeit.','Passt es dir','um drei Uhr?'],personal:'Your day and time'}],
    A2:[
      {kind:'Listen and repeat',prompt:'Explain a recent experience.',de:'Letztes Wochenende bin ich nach Hamburg gefahren.',en:'Last weekend I travelled to Hamburg.',chunks:['Letztes Wochenende','bin ich','nach Hamburg gefahren.']},
      {kind:'Shadow the rhythm',prompt:'Give a reason naturally.',de:'Ich bleibe heute zu Hause, weil ich mich nicht gut fühle.',en:'I am staying home today because I do not feel well.',chunks:['Ich bleibe heute zu Hause,','weil ich mich','nicht gut fühle.']},
      {kind:'Respond to Vivian',prompt:'Describe one thing you have done this week.',de:'Diese Woche habe ich viel gearbeitet und einen Freund besucht.',en:'This week I worked a lot and visited a friend.',chunks:['Diese Woche','habe ich viel gearbeitet','und einen Freund besucht.'],personal:'Write your experience first (optional)'},
      {kind:'Dialogue role',prompt:'Call to reschedule an appointment.',de:'Leider kann ich morgen nicht kommen. Können wir den Termin verschieben?',en:'Unfortunately I cannot come tomorrow. Can we reschedule?',chunks:['Leider kann ich','morgen nicht kommen.','Können wir den Termin','verschieben?'],personal:'Your proposed new time'}],
    B1:[
      {kind:'Listen and repeat',prompt:'State an opinion with a reason.',de:'Meiner Meinung nach sollte der öffentliche Nahverkehr verbessert werden.',en:'In my opinion, public transport should be improved.',chunks:['Meiner Meinung nach','sollte der öffentliche Nahverkehr','verbessert werden.']},
      {kind:'Shadow the rhythm',prompt:'Balance two perspectives.',de:'Einerseits ist Homeoffice praktisch, andererseits fehlt der persönliche Kontakt.',en:'On one hand remote work is practical; on the other, personal contact is missing.',chunks:['Einerseits ist Homeoffice praktisch,','andererseits fehlt','der persönliche Kontakt.']},
      {kind:'Respond to Vivian',prompt:'Give your view on learning online.',de:'Ich finde Onlinekurse hilfreich, weil man flexibel lernen kann.',en:'I find online courses useful because one can learn flexibly.',chunks:['Ich finde Onlinekurse hilfreich,','weil man','flexibel lernen kann.'],personal:'Plan your personal opinion (optional)'},
      {kind:'Dialogue role',prompt:'Politely disagree and add your argument.',de:'Ich verstehe Ihren Punkt, allerdings sehe ich das etwas anders.',en:'I understand your point; however, I see it somewhat differently.',chunks:['Ich verstehe Ihren Punkt,','allerdings sehe ich das','etwas anders.'],personal:'Your supporting reason'}]
  };
  const byId=id=>document.getElementById(id),page=new URL(location.href),level=['A1','A2','B1'].includes(page.searchParams.get('level'))?page.searchParams.get('level'):'A1',items=content[level],els={stage:byId('stageLabel'),count:byId('countLabel'),bar:byId('progressBar'),prompt:byId('prompt'),model:byId('modelText'),translation:byId('translation'),chunks:byId('chunks'),personal:byId('personal'),record:byId('record'),stop:byId('stop'),replay:byId('replay'),timer:byId('timer'),myAudio:byId('myAudio'),privacy:byId('privacy'),reflection:byId('reflection'),feedback:byId('feedback'),next:byId('next'),result:byId('result')};
  levelPill.textContent=`${level} SPEAKING`;document.querySelectorAll('.level-switch a').forEach(a=>a.classList.toggle('active',a.textContent===level));document.title=`${level} speaking studio — Fallweise`;
  let index=0,mediaRecorder=null,stream=null,parts=[],recordingUrl=null,started=0,activityStarted=Date.now(),tick=null,api=null,recordingKey=null,priorSkill={attempts:0,correct_attempts:0,current_streak:0};const ready=()=>new Promise(resolve=>{if(window.FallweiseProgress)resolve(window.FallweiseProgress);else addEventListener('fallweise:ready',e=>resolve(e.detail),{once:true})});ready().then(async x=>{api=x;if(api.client){const {data}=await api.client.from('skill_mastery').select('*').eq('skill_id',`speaking-${level.toLowerCase()}:confidence`).maybeSingle();if(data)priorSkill=data}});
  const db=()=>new Promise((resolve,reject)=>{const r=indexedDB.open('fallweise-speaking',1);r.onupgradeneeded=()=>r.result.createObjectStore('recordings',{keyPath:'key'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});async function saveBlob(key,blob){const d=await db();await new Promise((resolve,reject)=>{const tx=d.transaction('recordings','readwrite');tx.objectStore('recordings').put({key,blob,at:new Date().toISOString()});tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});d.close()}async function loadBlob(key){const d=await db(),row=await new Promise((resolve,reject)=>{const r=d.transaction('recordings').objectStore('recordings').get(key);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});d.close();return row?.blob}async function clearAll(){const d=await db();await new Promise((resolve,reject)=>{const tx=d.transaction('recordings','readwrite');tx.objectStore('recordings').clear();tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});d.close()}
  function speakText(text){window.FallweiseSpeech?.speakText(text)}
  async function render(){activityStarted=Date.now();const x=items[index];els.stage.textContent=x.kind;els.count.textContent=`${index+1} of ${items.length}`;els.bar.style.width=`${(index+1)/items.length*100}%`;els.prompt.textContent=x.prompt;els.model.textContent=x.de;els.translation.textContent=x.en;els.chunks.innerHTML='';x.chunks.forEach(part=>{const b=document.createElement('button');b.className='chunk';b.textContent=part;b.onclick=()=>speakText(part);els.chunks.appendChild(b)});els.personal.innerHTML=x.personal?`<label>${x.personal}</label><input maxlength="180" placeholder="Write a short plan before speaking">`:'';els.reflection.hidden=true;els.reflection.querySelectorAll('input').forEach(i=>i.checked=false);els.next.disabled=true;els.feedback.textContent='';els.myAudio.hidden=true;els.replay.disabled=true;recordingKey=`speaking:${level}:${index}`;const saved=await loadBlob(recordingKey);if(saved)attachRecording(saved);els.result.classList.remove('show')}
  function attachRecording(blob){if(recordingUrl)URL.revokeObjectURL(recordingUrl);recordingUrl=URL.createObjectURL(blob);els.myAudio.src=recordingUrl;els.myAudio.hidden=false;els.replay.disabled=false;els.reflection.hidden=false;els.next.disabled=false;els.privacy.textContent='Saved locally on this device. Replay and compare with Vivian.'}
  els.record.onclick=async()=>{try{els.next.disabled=true;stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true}});parts=[];mediaRecorder=new MediaRecorder(stream);mediaRecorder.ondataavailable=e=>{if(e.data.size)parts.push(e.data)};mediaRecorder.onstop=async()=>{const blob=new Blob(parts,{type:mediaRecorder.mimeType||'audio/webm'});await saveBlob(recordingKey,blob);attachRecording(blob);stream.getTracks().forEach(t=>t.stop());stream=null;clearInterval(tick);els.record.classList.remove('recording');els.record.disabled=false;els.stop.disabled=true;els.timer.textContent='Recording saved'};mediaRecorder.start();started=Date.now();els.record.classList.add('recording');els.record.disabled=true;els.stop.disabled=false;els.timer.textContent='0:00';tick=setInterval(()=>{const s=Math.floor((Date.now()-started)/1000);els.timer.textContent=`${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`},250)}catch(e){els.feedback.textContent=e.name==='NotAllowedError'?'Microphone permission was not granted. You can enable it in browser settings and try again.':'This browser could not start recording.'}}
  els.stop.onclick=()=>{if(mediaRecorder?.state==='recording')mediaRecorder.stop()};els.replay.onclick=()=>{els.myAudio.currentTime=0;els.myAudio.play()};
  async function saveReflection(){api=api||await ready();const x=items[index],checks=[...els.reflection.querySelectorAll('input:checked')].map(i=>i.value),now=new Date().toISOString(),attempts=Number(priorSkill.attempts||0)+index+1,correctAttempts=Number(priorSkill.correct_attempts||0)+index+1;await Promise.all([api.recordAttempt({exercise_id:`speaking:${level}:${index+1}`,skill_id:`speaking-${level.toLowerCase()}:confidence`,lesson_id:`speaking:${level}`,exercise_type:'speaking',answer:{reflection:checks,prompt:x.prompt,personal:els.personal.querySelector('input')?.value||'',recording:'local-only'},correct:true,hints_used:0,response_ms:Math.max(0,Date.now()-activityStarted),attempted_at:now}),api.saveLesson({lesson_id:`speaking:${level}`,status:index===items.length-1?'completed':'in_progress',mastery:(index+1)/items.length,current_step:index+1,total_steps:items.length,last_activity_at:now,...(index===0?{started_at:now}:{}),...(index===items.length-1?{completed_at:now}:{})}),api.saveSkill({skill_id:`speaking-${level.toLowerCase()}:confidence`,level,domain:'speaking',mastery:correctAttempts/attempts,attempts,correct_attempts:correctAttempts,current_streak:Number(priorSkill.current_streak||0)+index+1,last_practised_at:now})]);await api.flush()}
  els.next.onclick=async()=>{els.next.disabled=true;els.next.textContent='Saving…';await saveReflection();if(index===items.length-1){document.querySelectorAll('.stage-line,.progress,.prompt,.model,.chunks,.personal,.recorder,.privacy,.reflection,.next').forEach(x=>x.style.display='none');els.myAudio.hidden=true;els.result.classList.add('show');els.result.innerHTML=`<div class="kicker">Speaking session complete</div><h2>Four thoughts spoken aloud.</h2><p>You compared rhythm, sounds, and completeness without pretending that a machine can reliably judge your accent.</p><a href="dashboard.html">See speaking progress →</a>`;return}index++;els.next.textContent='Save reflection & continue →';await render()};
  document.getElementById('clearRecordings').onclick=async()=>{await clearAll();if(recordingUrl)URL.revokeObjectURL(recordingUrl);els.myAudio.hidden=true;els.replay.disabled=true;els.reflection.hidden=true;els.next.disabled=true;els.privacy.textContent='Local speaking recordings cleared.'};addEventListener('beforeunload',()=>{stream?.getTracks().forEach(t=>t.stop());if(recordingUrl)URL.revokeObjectURL(recordingUrl)});render();
})();
