(() => {
  if (!('speechSynthesis' in window)) return;
  const synth=window.speechSynthesis;
  const css=document.createElement('style');css.textContent=`
  .speakable{position:relative;padding-right:42px!important}.speak-btn{position:absolute;right:8px;top:8px;width:31px;height:31px;border:1px solid currentColor;border-radius:50%;background:var(--paper,#fffdf6);color:var(--green,#254f3d);display:grid;place-items:center;cursor:pointer;z-index:6;transition:transform .2s,background .2s;color .2s}.speak-btn:hover{transform:scale(1.1);background:var(--lime,#d9ed72)}.speak-btn.speaking{background:var(--green,#254f3d);color:white;animation:soundPulse 1.15s infinite}.speak-btn svg{width:16px;height:16px;fill:currentColor}@keyframes soundPulse{50%{box-shadow:0 0 0 7px rgba(217,237,114,.25)}}
  .speech-panel{position:fixed;left:18px;bottom:18px;z-index:95;background:var(--paper,#fffdf6);color:var(--ink,#18201d);border:1px solid var(--ink,#18201d);box-shadow:6px 6px 0 var(--blue,#8dc8d8);padding:10px;display:flex;align-items:center;gap:8px;font-size:11px}.speech-panel button,.speech-panel select{border:1px solid var(--line,#d8d4c8);background:white;color:inherit;padding:7px;cursor:pointer;font:inherit}.speech-panel button{width:31px}.speech-panel label{font-weight:700}.speech-status{position:fixed;left:18px;bottom:79px;z-index:96;background:var(--ink,#18201d);color:white;padding:8px 11px;font-size:11px;opacity:0;transform:translateY(8px);transition:.25s;pointer-events:none}.speech-status.show{opacity:1;transform:none}
  @media(max-width:650px){.speech-panel{left:10px;bottom:max(10px,env(safe-area-inset-bottom));padding:7px;gap:6px;border-radius:12px;box-shadow:4px 4px 0 var(--blue,#8dc8d8)}.speech-panel label{display:none}.speech-panel button,.speech-panel select{min-height:38px}.speech-status{left:10px;bottom:calc(max(10px,env(safe-area-inset-bottom)) + 58px)}.speak-btn{width:38px;height:38px;right:10px;top:10px}}
  @media(prefers-reduced-motion:reduce){.speak-btn.speaking{animation:none}}
  `;document.head.appendChild(css);
  const icon='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 9v6h4l5 4V5L8 9H4zm12.5 3a4.5 4.5 0 0 0-2.25-3.9v7.8A4.5 4.5 0 0 0 16.5 12zm-2.25-8.3v2.1a7 7 0 0 1 0 12.4v2.1a9 9 0 0 0 0-16.6z"/></svg>';
  const QWEN_SPEAKER='Vivian';
  const QWEN_MODEL='Qwen/Qwen3-TTS-12Hz-0.6B-CustomVoice';
  const TTS_BASE=(location.hostname==='127.0.0.1'||location.hostname==='localhost')?'http://127.0.0.1:8000':'';
  let voices=[],active=null,audio=null,premiumAvailable=false,rate=+(localStorage.getItem('fallweise-speech-rate')||.88),systemVoiceName=localStorage.getItem('fallweise-system-voice')||'';
  const clean=el=>{const c=el.cloneNode(true);c.querySelectorAll('button,.speak-btn,.en,.why,.use').forEach(x=>x.remove());return c.textContent.replace(/\s+/g,' ').replace(/[→·]/g,',').trim()};
  const germanVoices=()=>voices.filter(v=>/^de([-_]|$)/i.test(v.lang));
  function rank(v){let s=0,n=v.name.toLowerCase();if(v.localService)s+=3;if(/premium|enhanced|neural|natural|anna|petra|katja|conrad|vicki|seraphina|killian/.test(n))s+=7;if(/^de-de$/i.test(v.lang))s+=3;if(/google|microsoft|apple/.test(n))s+=2;return s}
  function selectedVoice(){let gs=germanVoices();return gs.find(v=>v.name===systemVoiceName)||gs.sort((a,b)=>rank(b)-rank(a))[0]||voices[0]}
  function loadVoices(){voices=synth.getVoices()}
  synth.onvoiceschanged=loadVoices;
  const panel=document.createElement('div');panel.className='speech-panel';panel.setAttribute('aria-label','Pronunciation controls');panel.innerHTML=`<button id="speechStop" title="Stop speech" aria-label="Stop speech">■</button><label for="speechRate">Speech speed</label><select id="speechRate" aria-label="Speech speed"><option value="0.72">Slow</option><option value="0.88">Learn</option><option value="1">Natural</option></select>`;document.body.appendChild(panel);panel.querySelector('#speechRate').value=String(rate);
  const status=document.createElement('div');status.className='speech-status';document.body.appendChild(status);let statusTimer;function showStatus(msg){status.textContent=msg;status.classList.add('show');clearTimeout(statusTimer);statusTimer=setTimeout(()=>status.classList.remove('show'),1800)}
  panel.querySelector('#speechStop').onclick=()=>{synth.cancel();if(audio){audio.pause();audio=null}setActive(null);showStatus('Playback stopped')};panel.querySelector('#speechRate').onchange=e=>{rate=+e.target.value;localStorage.setItem('fallweise-speech-rate',rate);showStatus(e.target.options[e.target.selectedIndex].text+' speed · Vivian')};
  async function detectPremium(){if(!TTS_BASE)return;try{const r=await fetch(TTS_BASE+'/api/tts/status',{signal:AbortSignal.timeout(1500)});if(!r.ok)return;premiumAvailable=true}catch(e){showStatus('Vivian unavailable · temporary system fallback')}}
  function setActive(btn){if(active)active.classList.remove('speaking');active=btn;if(active)active.classList.add('speaking')}
  async function cachedAudioUrl(text){const rateKey=rate===1?'1.0':String(rate),source=`${QWEN_MODEL}|${QWEN_SPEAKER}|${rateKey}|${text}`,bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(source)),hash=[...new Uint8Array(bytes)].map(x=>x.toString(16).padStart(2,'0')).join('');const url=`work/tts-cache/${hash}.wav`,r=await fetch(url,{method:'HEAD'});return r.ok?url:null}
  function browserSpeak(text,btn){const u=new SpeechSynthesisUtterance(text);u.lang='de-DE';u.rate=rate;u.pitch=1;const v=selectedVoice();if(v)u.voice=v;u.onstart=()=>{setActive(btn);showStatus('System voice · listen and repeat')};u.onend=u.onerror=()=>setActive(null);synth.speak(u)}
  async function speak(text,btn){synth.cancel();if(audio){audio.pause();audio=null}if(!text)return;setActive(btn);showStatus('Vivian · preparing…');try{let url=await cachedAudioUrl(text);if(!url){if(!TTS_BASE)throw new Error('Audio unavailable');const r=await fetch(TTS_BASE+'/api/tts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text,rate,speaker:QWEN_SPEAKER})});if(!r.ok)throw new Error('Qwen unavailable');url=URL.createObjectURL(await r.blob())}audio=new Audio(url);audio.onplay=()=>showStatus('Vivian · '+({0.72:'Slow',0.88:'Learn',1:'Natural'}[rate]||'Learn'));audio.onended=audio.onerror=()=>{setActive(null);audio=null};await audio.play()}catch(e){showStatus('Temporary system fallback');setActive(null);browserSpeak(text,btn)}}
  const selectors=['.de','.german','.hero-sentence','.big-example','#tenseGerman','.sentence'];
  function installSpeakers(root=document){const found=selectors.flatMap(s=>[...(root.matches?.(s)?[root]:[]),...root.querySelectorAll?.(s)||[]]);[...new Set(found)].filter(el=>!el.querySelector(':scope > .speak-btn')).forEach(el=>{el.classList.add('speakable');const b=document.createElement('button');b.className='speak-btn';b.type='button';b.title='Hear German pronunciation';b.setAttribute('aria-label',`Hear ${clean(el)} pronounced`);b.innerHTML=icon;b.onclick=e=>{e.stopPropagation();if(active===b){synth.cancel();setActive(null)}else speak(clean(el),b)};el.appendChild(b)})}
  installSpeakers();
  let installQueued=false;new MutationObserver(()=>{if(installQueued)return;installQueued=true;requestAnimationFrame(()=>{installQueued=false;installSpeakers()})}).observe(document.body,{childList:true,subtree:true});
  document.addEventListener('visibilitychange',()=>{if(document.hidden){synth.cancel();setActive(null)}});addEventListener('beforeunload',()=>synth.cancel());loadVoices();detectPremium();
})();
