(() => {
  const params=new URLSearchParams(location.search),requestedLevel=(params.get('level')||'A1').toUpperCase(),level=['A1','A2','B1'].includes(requestedLevel)?requestedLevel:'A1';
  const data=level==='A1'?{level:'A1',...window.A1Vocabulary}:window.AdvancedVocabulary[level],{units,items,count}=data,requested=params.get('unit'),reviewId=params.get('review');
  const els={grid:document.getElementById('unitGrid'),search:document.getElementById('vocabSearch'),searchCount:document.getElementById('searchCount'),lesson:document.getElementById('unitLesson'),practice:document.getElementById('unitPractice'),title:document.getElementById('unitTitle'),goal:document.getElementById('unitGoal'),kicker:document.getElementById('unitKicker'),words:document.getElementById('wordList'),start:document.getElementById('startPractice'),count:document.getElementById('count'),kind:document.getElementById('exerciseKind'),question:document.getElementById('question'),answers:document.getElementById('answers'),feedback:document.getElementById('feedback'),next:document.getElementById('next'),result:document.getElementById('vocabResult'),mastery:document.getElementById('vocabMastery')};
  document.querySelectorAll('[data-word-count]').forEach(el=>el.textContent=count);document.querySelectorAll('[data-level]').forEach(el=>el.textContent=level);document.querySelector(`[data-level-link="${level}"]`)?.classList.add('active');
  document.title=`${level} Vocabulary Curriculum — Fallweise`;
  document.getElementById('levelLead').textContent=level==='A1'?'Build a complete everyday foundation in twenty-word chapters with visual memory cues, sentences, listening, and retrieval.':`Grow beyond the foundation with ${count} authored ${level} entries. This is a clearly counted expansion that will continue to grow.`;
  document.getElementById('countDescription').textContent=`distinct ${level} entries · ${units.length} practical units · article and plural for every noun · adaptive retrieval and progress saving`;
  let progress=new Map(),unit=units.find(row=>row.id===requested)||null,api=null,activities=[],index=0,locked=false,results=[],started=performance.now(),baseline={};
  const ready=()=>new Promise(resolve=>{if(window.FallweiseProgress)resolve(window.FallweiseProgress);else addEventListener('fallweise:ready',e=>resolve(e.detail),{once:true})});
  const display=item=>item.article?`${item.article} ${item.de}`:item.de,normalize=value=>String(value).trim().toLocaleLowerCase('de-DE').replace(/[.!?„“"]/g,'').replace(/\s+/g,' '),shuffled=array=>[...array].sort(()=>Math.random()-.5);
  const distract=(item,field)=>shuffled(unit.items.filter(row=>row!==item).map(row=>field==='display'?display(row):row[field]).filter((value,i,all)=>value&&all.indexOf(value)===i)).slice(0,3),choices=(correct,others)=>shuffled([correct,...others]);
  const progressId=id=>`vocabulary-${level.toLowerCase()}:${id}`,levelUrl=id=>`vocabulary-path.html?level=${level}&unit=${id}#unitLesson`;
  function renderUnits(filter=''){const query=normalize(filter),matches=units.filter(row=>!query||normalize(`${row.title} ${row.goal} ${row.items.map(item=>`${item.de} ${item.en}`).join(' ')}`).includes(query));els.searchCount.textContent=`${matches.length} ${matches.length===1?'UNIT':'UNITS'} · ${matches.reduce((sum,row)=>sum+row.items.length,0)} WORDS`;els.grid.innerHTML=matches.length?matches.map(row=>{const saved=progress.get(progressId(row.id)),label=saved?.status==='completed'?`✓ ${Math.round(Number(saved.mastery||0)*100)}% recalled`:saved?'Continue practice':'Not started';return `<a class="unit" href="${levelUrl(row.id)}"><div class="unit-top"><span class="unit-icon" aria-hidden="true">${row.icon}</span><span class="unit-number">${level} · UNIT ${String(units.indexOf(row)+1).padStart(2,'0')}</span></div><h3>${row.title}</h3><p>${row.goal}</p><div class="unit-foot"><span>${row.items.length} words</span><span class="unit-progress">${label} →</span></div></a>`}).join(''):'<div class="empty">No match yet. Try a German word, its English meaning, or a broader topic.</div>'}
  els.search.oninput=e=>renderUnits(e.target.value);
  function renderUnit(){if(!unit)return;els.lesson.hidden=false;els.kicker.textContent=`${level} · Unit ${String(units.indexOf(unit)+1).padStart(2,'0')} · ${unit.items.length} words`;els.title.textContent=unit.title;els.goal.textContent=unit.goal+'. Reveal the meaning, inspect the memory scene, and hear the word or example sentence.';els.words.innerHTML=unit.items.map(item=>`<article class="curriculum-word" tabindex="0" role="button" aria-label="Reveal the meaning of ${display(item)}"><div class="word-visual">${FallweiseIllustrations.scene(item,unit)}</div><span class="word-type">${item.type}${item.article?` · ${item.article}`:''}</span><div class="german">${display(item)}</div><div class="plural">${item.type==='noun'?`Plural: ${item.plural}`:'&nbsp;'}</div><div class="english">${item.en}</div><div class="word-example sentence">${item.example}</div><span class="tap">TAP TO REVEAL</span></article>`).join('');els.words.querySelectorAll('.curriculum-word').forEach(card=>{const toggle=()=>card.classList.toggle('revealed');card.onclick=e=>{if(!e.target.closest('.speak-btn'))toggle()};card.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();toggle()}}});if(location.hash==='#unitLesson')requestAnimationFrame(()=>els.lesson.scrollIntoView({block:'start'}))}
  function buildActivities(){activities=unit.items.map((item,i)=>{const mode=i%7;if(item.type==='noun'&&mode===1)return{item,type:'article',skill:'form',kind:'Article retrieval',prompt:`Which article belongs with ${item.de}?`,options:['der','die','das'],correct:item.article};if(mode===2)return{item,type:'sentence_listening',skill:'listening',kind:'Sentence listening',prompt:'Listen to Vivian. Which meaning fits the sentence?',options:choices(item.exampleEn,distract(item,'exampleEn')),correct:item.exampleEn,audioText:item.example};if(mode===3)return{item,type:'dictation',skill:'listening',kind:'Sentence dictation',prompt:'Listen, then type the complete German sentence.',answers:[item.example],correct:item.example,audioText:item.example};if(mode===4)return{item,type:'spelling',skill:'meaning',kind:'Produce the German',prompt:`Type the German ${item.type==='noun'?'noun (article not needed)':'word or phrase'} for “${item.en}”.`,answers:[item.de],correct:item.de};if(mode===5)return{item,type:'matching',skill:'meaning',kind:'Match the pair',prompt:`Which pair correctly matches “${item.en}”?`,options:choices(`${display(item)} — ${item.en}`,distract(item,'display').map((value,j)=>`${value} — ${distract(item,'en')[j]||item.en}`)),correct:`${display(item)} — ${item.en}`};if(mode===6)return{item,type:'reverse',skill:'meaning',kind:'English to German',prompt:`Which German item means “${item.en}”?`,options:choices(display(item),distract(item,'display')),correct:display(item)};return{item,type:'meaning',skill:'meaning',kind:'Meaning from memory',prompt:`What does “${display(item)}” mean?`,options:choices(item.en,distract(item,'en')),correct:item.en}});if(reviewId){const parts=reviewId.split(':'),item=unit.items.find(row=>row.id===parts[2]);if(item)activities=[activities.find(a=>a.item===item)||activities[0]]}}
  function score(skill){const prior=baseline[skill]||{attempts:0,correct_attempts:0},session=results.filter(r=>r.skill===skill),attempts=prior.attempts+session.length,correct=prior.correct_attempts+session.filter(r=>r.correct).length;return attempts?Math.round(correct/attempts*100):0}
  function renderMastery(){els.mastery.innerHTML=[['meaning','Meaning'],['form','Form'],['listening','Listening']].map(([id,label])=>`<div><span>${label}</span><b>${score(id)}%</b></div>`).join('')}
  function renderActivity(){locked=false;started=performance.now();const a=activities[index];els.count.textContent=`ACTIVITY ${index+1} OF ${activities.length}`;els.kind.textContent=a.kind;els.question.textContent=a.prompt;els.answers.innerHTML='';els.feedback.textContent='';els.next.style.display='none';els.result.classList.remove('show');if(a.audioText){const audio=document.createElement('div');audio.className='sentence audio-prompt';audio.textContent=a.audioText;els.answers.appendChild(audio)}if(a.options)a.options.forEach(option=>{const button=document.createElement('button');button.className='answer';button.textContent=option;button.onclick=()=>submit(normalize(option)===normalize(a.correct),button,option);els.answers.appendChild(button)});else{const form=document.createElement('form');form.className='vocab-form';form.innerHTML='<input aria-label="Your answer" autocomplete="off" autocapitalize="none" required><button>Check</button>';form.onsubmit=e=>{e.preventDefault();const input=form.querySelector('input'),value=input.value;submit(a.answers.some(answer=>normalize(answer)===normalize(value)),input,value)};els.answers.appendChild(form)}}
  async function submit(correct,target,selected){if(locked)return;locked=true;const a=activities[index],elapsed=Math.round(performance.now()-started);target.classList?.add(correct?'correct':'wrong');if(a.options)[...els.answers.querySelectorAll('.answer')].find(b=>normalize(b.textContent)===normalize(a.correct))?.classList.add('correct');els.feedback.textContent=correct?`Richtig! ${display(a.item)} · ${a.item.en}. ${a.item.example}`:`Not yet. The answer is “${a.correct}”. Example: ${a.item.example}`;els.next.style.display='inline-block';els.next.disabled=true;els.next.textContent=index===activities.length-1?'See my result →':'Next activity →';results.push({skill:a.skill,correct});renderMastery();await save(a,correct,selected,elapsed);els.next.disabled=false}
  async function save(a,correct,selected,response_ms){api=api||await ready();const now=new Date().toISOString(),done=index===activities.length-1,lessonId=progressId(unit.id),mastery=results.filter(r=>r.correct).length/activities.length,skillId=`vocab-${level.toLowerCase()}-${unit.id}:${a.skill}`,prior=baseline[a.skill]||{attempts:0,correct_attempts:0,current_streak:0},session=results.filter(r=>r.skill===a.skill),attempts=prior.attempts+session.length,correctAttempts=prior.correct_attempts+session.filter(r=>r.correct).length,exerciseType=a.type==='spelling'?'fill_blank':a.type==='dictation'?'dictation':a.type==='matching'?'matching':a.type.includes('listening')?'listening':'choice';api.recordAttempt({exercise_id:`vocab:${level}-${unit.id}:${a.item.id}:${a.type}`,skill_id:skillId,lesson_id:lessonId,exercise_type:exerciseType,answer:{selected,prompt:a.prompt},correct,hints_used:0,response_ms,attempted_at:now});if(!reviewId)api.saveLesson({lesson_id:lessonId,status:done?'completed':'in_progress',mastery,current_step:index+1,total_steps:activities.length,last_activity_at:now,...(index===0?{started_at:now}:{}),...(done?{completed_at:now}:{})});api.saveSkill({skill_id:skillId,level,domain:a.skill==='listening'?'listening':'vocabulary',mastery:correctAttempts/attempts,attempts,correct_attempts:correctAttempts,current_streak:correct?(prior.current_streak||0)+1:0,last_practised_at:now});const due=new Date(now);due.setMinutes(due.getMinutes()+(correct?1440:10));api.saveReview({item_id:`vocab:${level}-${unit.id}:${a.item.id}:${a.type}`,skill_id:skillId,item_type:a.type==='article'?'article':a.type.includes('listening')?'listening':a.type==='dictation'||a.type==='spelling'?'spelling':'meaning',interval_days:correct?1:0,ease_factor:correct?2.5:2.3,repetitions:correct?1:0,lapses:correct?0:1,due_at:due.toISOString(),last_reviewed_at:now,suspended:false})}
  function finish(){const correct=results.filter(r=>r.correct).length;els.question.textContent='';els.answers.innerHTML='';els.feedback.textContent='';els.kind.textContent='';els.next.style.display='none';els.result.classList.add('show');els.result.innerHTML=`<div class="kicker" style="color:var(--lime)">${level} unit complete</div><h3>${correct}/${activities.length} retrieved</h3><p>Difficult items now return sooner in spaced review.</p><a href="vocabulary-path.html?level=${level}#curriculum">Choose the next unit →</a>`}
  function startPractice(){els.practice.hidden=false;els.practice.scrollIntoView({behavior:'smooth'});buildActivities();index=0;results=[];renderMastery();renderActivity()}els.start.onclick=startPractice;els.next.onclick=()=>index===activities.length-1?finish():(index++,renderActivity());renderUnits();renderUnit();
  ready().then(async value=>{api=value;if(api.client){const [{data:rows},{data:skills}]=await Promise.all([api.client.from('lesson_progress').select('*').like('lesson_id',`vocabulary-${level.toLowerCase()}:%`),unit?api.client.from('skill_mastery').select('*').like('skill_id',`vocab-${level.toLowerCase()}-${unit.id}:%`):Promise.resolve({data:[]})]);progress=new Map((rows||[]).map(row=>[row.lesson_id,row]));(skills||[]).forEach(row=>baseline[row.skill_id.split(':').pop()]=row);renderUnits(els.search.value);renderMastery()}if(reviewId&&unit)startPractice()});
})();
