(() => {
  const SESSION_ENDPOINT='https://fallweise-voice-session.arpithpmuddi-0ee.workers.dev/api/livekit/session',AGENT_TOPIC='fallweise.agent',LESSON_TOPIC='fallweise.lesson',LOCAL_PROGRESS_KEY='fallweise-voice-a1-progress',LOCAL_WORD_KEY='fallweise-voice-a1-words';
  const coreCurriculum=[
    {id:'01-meet-greet',type:'WORDS',title:'Meet & greet',goal:'Greet someone and introduce yourself.',steps:[
      {kind:'NOTICE',visual:'Hallo! Ich heiße Mia.',hint:'Hallo means hello. Ich heiße… introduces your name.',line:'Welcome to your A1 journey. Listen: Hallo! Ich heiße Mia. That means, hello, my name is Mia.'},
      {kind:'YOUR TURN',visual:'My name is… → Ich heiße …',hint:'Say the German phrase with your name.',line:'Now introduce yourself. Say: Ich heiße, followed by your name.',answers:['ich heisse','ich heiße'],success:'Sehr gut. You introduced yourself in German.',retry:'Begin with Ich heiße, then say your name.'},
      {kind:'REAL EXCHANGE',visual:'Wie heißt du?',hint:'Answer with: Ich heiße …',line:'I will ask your name. Wie heißt du?',answers:['ich heisse','ich heiße'],success:'Freut mich! Nice to meet you.',retry:'Answer: Ich heiße, and then your name.'}]},
    {id:'02-who-does-what',type:'GRAMMAR',title:'Who does what?',goal:'Build a sentence with a doer and an object.',steps:[
      {kind:'NOTICE',visual:'Der Mann sieht den Hund.',hint:'der Mann does it · den Hund receives it',line:'German cases show each word’s job. Der Mann sees. Den Hund is seen. Listen: Der Mann sieht den Hund.'},
      {kind:'YOUR TURN',visual:'the dog → der Hund / den Hund',hint:'After sieht, masculine der becomes den.',line:'Complete this sentence: Der Mann sieht, the dog.',answers:['den hund'],success:'Exactly. Der Mann sieht den Hund.',retry:'The dog is the object, so say: den Hund.'},
      {kind:'TRANSFER',visual:'The woman sees the man.',hint:'Die Frau sieht den Mann.',line:'Now say: The woman sees the man.',answers:['die frau sieht den mann'],success:'Perfect. You marked the doer and object clearly.',retry:'Say: Die Frau sieht den Mann.'}]},
    {id:'03-talk-now',type:'SPEAKING',title:'Talk about now',goal:'Use present-tense verbs in useful sentences.',steps:[
      {kind:'NOTICE',visual:'ich lerne · du lernst',hint:'The verb ending changes with the person.',line:'To talk about now, say: Ich lerne Deutsch. With du, the ending changes: Du lernst Deutsch.'},
      {kind:'YOUR TURN',visual:'I learn German.',hint:'ich + lerne',line:'How do you say: I learn German?',answers:['ich lerne deutsch'],success:'Richtig. Ich lerne Deutsch.',retry:'Say: Ich lerne Deutsch.'},
      {kind:'TRANSFER',visual:'I live in Berlin.',hint:'wohnen → ich wohne',line:'Now say: I live in Berlin.',answers:['ich wohne in berlin'],success:'Excellent. You can talk about what is happening now.',retry:'Say: Ich wohne in Berlin.'}]},
    {id:'04-everyday-world',type:'WORDS',title:'Your everyday world',goal:'Use essential home, food, and travel words.',steps:[
      {kind:'WORD SET',visual:'das Haus · das Brot · der Zug',hint:'home · bread · train',line:'Three useful everyday words: das Haus, the house. Das Brot, the bread. Der Zug, the train.'},
      {kind:'YOUR TURN',visual:'the bread → ?',hint:'Remember the neuter article.',line:'How do you say: the bread?',answers:['das brot'],success:'Yes. Das Brot.',retry:'Say: das Brot.'},
      {kind:'USE IT',visual:'I travel by train.',hint:'Ich fahre mit dem Zug.',line:'Say the useful sentence: I travel by train.',answers:['ich fahre mit dem zug'],success:'Great. Ich fahre mit dem Zug.',retry:'Say: Ich fahre mit dem Zug.'}]},
    {id:'05-questions-order',type:'GRAMMAR',title:'Questions & word order',goal:'Ask for information with the verb in the right place.',steps:[
      {kind:'NOTICE',visual:'Wo wohnst du?',hint:'Question word · verb · person',line:'In a W question, put the verb directly after the question word. Wo wohnst du? Where do you live?'},
      {kind:'YOUR TURN',visual:'Where do you live?',hint:'Wo · wohnst · du?',line:'Ask me: Where do you live?',answers:['wo wohnst du'],success:'Exactly. Wo wohnst du?',retry:'Say: Wo wohnst du?'},
      {kind:'YES OR NO',visual:'Sprichst du Deutsch?',hint:'Verb comes first.',line:'Now ask: Do you speak German?',answers:['sprichst du deutsch'],success:'Perfect question word order.',retry:'Say: Sprichst du Deutsch?'}]},
    {id:'06-can-want-must',type:'SPEAKING',title:'Can, want, must',goal:'Express ability and wishes with modal verbs.',steps:[
      {kind:'NOTICE',visual:'Ich kann Deutsch sprechen.',hint:'Modal in position 2 · main verb at the end',line:'With a modal verb, the second verb moves to the end. Ich kann Deutsch sprechen.'},
      {kind:'YOUR TURN',visual:'I can speak German.',hint:'Ich kann · Deutsch · sprechen.',line:'Say: I can speak German.',answers:['ich kann deutsch sprechen'],success:'Genau. Ich kann Deutsch sprechen.',retry:'Say: Ich kann Deutsch sprechen.'},
      {kind:'TRANSFER',visual:'I want to learn German.',hint:'Ich will Deutsch lernen.',line:'Now say: I want to learn German.',answers:['ich will deutsch lernen','ich möchte deutsch lernen','ich mochte deutsch lernen'],success:'Very good. Your modal verb frame is working.',retry:'Say: Ich will Deutsch lernen.'}]},
    {id:'07-hear-spell',type:'SOUNDS',title:'Hear it, spell it',goal:'Recognize German umlauts and ß.',steps:[
      {kind:'LISTEN',visual:'a → ä · o → ö · u → ü',hint:'Umlauts are distinct German sounds.',line:'Listen to the umlauts: ä, as in Käse. Ö, as in schön. Ü, as in fünf.'},
      {kind:'YOUR TURN',visual:'fünf',hint:'Round your lips for ü.',line:'Repeat the number five: fünf.',answers:['fünf','funf'],success:'Good. Fünf.',retry:'Round your lips and say: fünf.'},
      {kind:'SOUND LINK',visual:'Straße',hint:'ß sounds like a sharp s.',line:'Repeat this word with a clear s sound: Straße.',answers:['straße','strasse'],success:'Sehr gut. Straße.',retry:'Say: Straße.'}]},
    {id:'08-numbers-time',type:'DAILY LIFE',title:'Numbers, time & dates',goal:'Tell the time and make a simple appointment.',steps:[
      {kind:'NOTICE',visual:'Es ist drei Uhr.',hint:'It is three o’clock.',line:'To tell the hour, say: Es ist drei Uhr.'},
      {kind:'YOUR TURN',visual:'It is five o’clock.',hint:'Es ist fünf Uhr.',line:'How do you say: It is five o’clock?',answers:['es ist fünf uhr','es ist funf uhr'],success:'Correct. Es ist fünf Uhr.',retry:'Say: Es ist fünf Uhr.'},
      {kind:'APPOINTMENT',visual:'am Montag um zehn Uhr',hint:'on Monday at ten',line:'Say: on Monday at ten o’clock.',answers:['am montag um zehn uhr'],success:'Excellent. You can state an appointment time.',retry:'Say: am Montag um zehn Uhr.'}]},
    {id:'09-real-conversations',type:'DIALOGUE',title:'Real conversations',goal:'Handle a polite café exchange.',steps:[
      {kind:'DIALOGUE',visual:'Ich möchte einen Kaffee, bitte.',hint:'I would like a coffee, please.',line:'At a café, a friendly request is: Ich möchte einen Kaffee, bitte.'},
      {kind:'YOUR TURN',visual:'A coffee, please.',hint:'Ich möchte …',line:'Order a coffee politely.',answers:['ich möchte einen kaffee bitte','ich mochte einen kaffee bitte'],success:'Gern. Ein Kaffee. That sounded natural.',retry:'Say: Ich möchte einen Kaffee, bitte.'},
      {kind:'CLOSE',visual:'Danke! · Bitte!',hint:'thank you · you’re welcome',line:'I hand you the coffee. What do you say?',answers:['danke','danke schön','vielen dank'],success:'Bitte schön! You completed a real exchange.',retry:'Say: Danke.'}]},
    {id:'10-no-mine-yours',type:'GRAMMAR',title:'No, mine & yours',goal:'Negate nouns and express possession.',steps:[
      {kind:'NOTICE',visual:'ein Auto → kein Auto',hint:'Use kein to negate a noun with ein.',line:'To say no car, change ein to kein. Ich habe kein Auto.'},
      {kind:'YOUR TURN',visual:'I have no car.',hint:'Ich habe kein Auto.',line:'Say: I have no car.',answers:['ich habe kein auto'],success:'Exactly. Ich habe kein Auto.',retry:'Say: Ich habe kein Auto.'},
      {kind:'POSSESSION',visual:'Das ist mein Buch.',hint:'That is my book.',line:'Now say: That is my book.',answers:['das ist mein buch'],success:'Perfect. You can negate and show ownership.',retry:'Say: Das ist mein Buch.'}]},
    {id:'11-everyday-life',type:'SKILLS',title:'Everyday life lab',goal:'Describe one part of your daily routine.',steps:[
      {kind:'ROUTINE',visual:'Ich arbeite am Morgen.',hint:'I work in the morning.',line:'Let’s build a routine. Listen: Ich arbeite am Morgen.'},
      {kind:'YOUR TURN',visual:'I work in the morning.',hint:'Ich arbeite am Morgen.',line:'Now say the sentence yourself.',answers:['ich arbeite am morgen'],success:'Good. Ich arbeite am Morgen.',retry:'Say: Ich arbeite am Morgen.'},
      {kind:'CONNECT',visual:'Am Abend lerne ich Deutsch.',hint:'Time first · verb second',line:'Say: In the evening I learn German.',answers:['am abend lerne ich deutsch'],success:'Excellent. Your routine now has two useful parts.',retry:'Say: Am Abend lerne ich Deutsch.'}]},
    {id:'12-speak-replay',type:'SPEAKING',title:'Speak & replay',goal:'Bring your A1 patterns together in one introduction.',steps:[
      {kind:'MISSION',visual:'Name · home · German',hint:'Link three short ideas.',line:'Your final A1 speaking mission is a short introduction: your name, where you live, and that you learn German.'},
      {kind:'BUILD',visual:'Ich heiße … Ich wohne in …',hint:'Say both sentences with your own details.',line:'Tell me your name and where you live.',answers:['ich heiße','ich heisse'],success:'Wonderful. Now add your learning goal.',retry:'Start with Ich heiße, then say: Ich wohne in, and your city.'},
      {kind:'FINAL RECALL',visual:'Ich lerne Deutsch.',hint:'Finish confidently.',line:'Complete your introduction by saying: I learn German.',answers:['ich lerne deutsch'],success:'Ausgezeichnet. You completed your A1 voice journey.',retry:'Say: Ich lerne Deutsch.'}]}
  ];
  const display=item=>item.article?`${item.article} ${item.de}`:item.de;
  function vocabularySteps(items,unit,batch){
    const list=items.map(item=>`${display(item)}, ${item.en}`).join('. '),contrast=items.slice(0,3).map(display).join(' · '),steps=[
      {kind:'INTRODUCE',visual:items.map(display).join(' · '),hint:`Five new words from ${unit.title}.`,line:`Here are five useful words. ${list}. Listen once, then I will help you retrieve them.`},
      {kind:'DISTINGUISH',visual:contrast,hint:'Notice the sound, meaning, and article.',line:`Listen to the first three again: ${items.slice(0,3).map(item=>`${display(item)} means ${item.en}`).join('. ')}.`}
    ];
    items.forEach((item,wordIndex)=>steps.push({kind:'SPOKEN RECALL',visual:`${item.en} → ?`,hint:item.type==='noun'?`Say the article and noun · word ${wordIndex+1} of 5`:`Say the German · word ${wordIndex+1} of 5`,line:`How do you say ${item.en} in German?`,answers:[display(item),item.de],success:`Richtig. ${display(item)} means ${item.en}.`,retry:`Listen once more: ${display(item)}. Now say ${display(item)}.`,item}));
    const use=items.find(item=>item.example)||items[0];steps.push({kind:'USE IT',visual:use.example,hint:`Use ${display(use)} in a complete thought.`,line:`Now use one word in context. Repeat: ${use.example}`,answers:[use.example],success:`Excellent. ${use.example}`,retry:`Say the complete sentence: ${use.example}`,item:use});
    return steps;
  }
  const vocabularySessions=(window.A1Vocabulary?.units||[]).flatMap((unit,unitIndex)=>Array.from({length:4},(_,batch)=>{const items=unit.items.slice(batch*5,batch*5+5);return{id:`vocab-${unit.id}-${batch+1}`,type:'VOCAB',title:`${unit.title} · ${batch+1}/4`,goal:`${unit.goal} Five words at a time.`,unit,batch,items,wordStart:unitIndex*20+batch*5,steps:vocabularySteps(items,unit,batch)}}));
  const unitsAfterChapter=[2,2,2,3,2,2,2,3,2,2,2,3];let unitCursor=0;
  const curriculum=coreCurriculum.flatMap((lesson,index)=>{const count=unitsAfterChapter[index],sessions=vocabularySessions.slice(unitCursor*4,(unitCursor+count)*4);unitCursor+=count;return[lesson,...sessions]});
  const $=id=>document.getElementById(id),ui={start:$('start'),mic:$('mic'),pause:$('pause'),status:$('status'),dot:$('liveDot'),bar:$('progressBar'),kind:$('stepKind'),visual:$('visual'),hint:$('hint'),mia:$('miaLine'),learner:$('learnerLine'),wave:$('voiceWave'),canvas:$('waveCanvas'),fallback:$('fallback'),typed:$('typed'),send:$('send'),meta:$('lessonMeta'),journey:$('journey'),toggle:$('journeyToggle'),close:$('journeyClose'),list:$('journeyList'),journeyBar:$('journeyBar'),journeyCount:$('journeyCount'),chapterCount:$('chapterCount'),tabs:document.querySelector('.journey-tabs')};
  let api,LiveKit,room,lessonIndex=0,index=0,steps=curriculum[0].steps,mode='idle',paused=false,processing=false,agentReady=false,pendingSpeech=null,speechSerial=0,agentTimer,highlightTimer,speechTimer,audioContext,analyser,waveFrame,journeyView='course';const progress=new Map(),wordProgress=new Map();
  const ready=()=>new Promise(resolve=>window.FallweiseProgress?resolve(window.FallweiseProgress):addEventListener('fallweise:ready',e=>resolve(e.detail),{once:true}));
  const normalize=s=>s.toLowerCase().normalize('NFKD').replace(/[^a-zäöüß ]/g,'').replace(/\s+/g,' ').trim(),wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
  const lessonId=(lesson=curriculum[lessonIndex])=>`voice-tutor:A1:${lesson.id}`;
  function loadLocalProgress(){try{const saved=JSON.parse(localStorage.getItem(LOCAL_PROGRESS_KEY)||'{}');Object.values(saved).forEach(row=>{if(row?.lesson_id)progress.set(row.lesson_id,row)})}catch{localStorage.removeItem(LOCAL_PROGRESS_KEY)}}
  function loadLocalWords(){try{const saved=JSON.parse(localStorage.getItem(LOCAL_WORD_KEY)||'{}');Object.entries(saved).forEach(([id,row])=>wordProgress.set(id,row))}catch{localStorage.removeItem(LOCAL_WORD_KEY)}}
  function saveLocalProgress(row){let saved={};try{saved=JSON.parse(localStorage.getItem(LOCAL_PROGRESS_KEY)||'{}')}catch{}saved[row.lesson_id]=row;localStorage.setItem(LOCAL_PROGRESS_KEY,JSON.stringify(saved))}
  function saveLocalWord(item,correct){const current=wordProgress.get(item.id)||{attempts:0,correct:0},row={attempts:current.attempts+1,correct:current.correct+(correct?1:0),learned:current.learned||correct,lastPractisedAt:new Date().toISOString()};wordProgress.set(item.id,row);localStorage.setItem(LOCAL_WORD_KEY,JSON.stringify(Object.fromEntries(wordProgress)));renderJourney()}
  function mergeProgress(row){const current=progress.get(row.lesson_id);if(!current||row.status==='completed'&&current.status!=='completed'||row.status===current.status&&new Date(row.last_activity_at||0)>=new Date(current.last_activity_at||0))progress.set(row.lesson_id,row)}
  function render(){const lesson=curriculum[lessonIndex],s=steps[index],position=lesson.type==='VOCAB'?`WORDS ${lesson.wordStart+1}–${lesson.wordStart+5} OF 540`:`LESSON ${coreCurriculum.indexOf(lesson)+1} OF ${coreCurriculum.length}`;ui.meta.textContent=`A1 · ${position} · ACTIVITY ${index+1} OF ${steps.length}`;ui.kind.textContent=s.kind;ui.visual.textContent=s.visual;ui.hint.textContent=`${lesson.title} · ${s.hint}`;ui.bar.style.width=`${(index+1)/steps.length*100}%`;ui.learner.textContent='';renderJourney()}
  function lessonButton(lesson,i,label){const row=progress.get(lessonId(lesson)),status=i===lessonIndex?'current':row?.status==='completed'?'complete':row?.status==='in_progress'?'continue':'ready';return `<button type="button" data-lesson="${i}" class="journey-item ${status}" aria-current="${i===lessonIndex?'step':'false'}"><span>${label}</span><b>${lesson.title}</b><small>${status==='complete'?'Complete ✓':status==='current'?`Current · ${index+1}/${steps.length}`:status==='continue'?'Continue':'Ready'}</small></button>`}
  function renderJourney(){const learned=[...wordProgress.values()].filter(row=>row.learned).length,complete=curriculum.filter(l=>progress.get(lessonId(l))?.status==='completed').length;ui.journeyCount.textContent=`${learned} of 540 words learned`;ui.chapterCount.textContent=`${complete} of ${curriculum.length} voice sessions complete`;ui.journeyBar.style.width=`${learned/540*100}%`;ui.tabs.querySelectorAll('button').forEach(button=>button.classList.toggle('active',button.dataset.view===journeyView));if(journeyView==='course'){ui.list.innerHTML=coreCurriculum.map((lesson,n)=>{const i=curriculum.indexOf(lesson);return lessonButton(lesson,i,`${String(n+1).padStart(2,'0')} · ${lesson.type}`)}).join('');return}ui.list.innerHTML=window.A1Vocabulary.units.map((unit,u)=>{const sessions=vocabularySessions.filter(lesson=>lesson.unit===unit),learnedInUnit=unit.items.filter(item=>wordProgress.get(item.id)?.learned).length;return `<section class="word-unit"><button type="button" class="word-unit-head" data-unit-toggle="${unit.id}" aria-expanded="${sessions.some(lesson=>curriculum.indexOf(lesson)===lessonIndex)}"><span>${unit.icon} UNIT ${String(u+1).padStart(2,'0')}</span><b>${unit.title}</b><small>${learnedInUnit}/20 learned</small></button><div class="word-batches">${sessions.map((lesson,b)=>lessonButton(lesson,curriculum.indexOf(lesson),`SET ${b+1} · WORDS ${b*5+1}–${b*5+5}`)).join('')}</div></section>`}).join('')}
  function chooseLesson(next,step=0){lessonIndex=next;steps=curriculum[next].steps;index=Math.min(step,steps.length-1);history.replaceState({},'',`${location.pathname}?lesson=${curriculum[next].id}`);render()}
  function toggleJourney(open=!ui.journey.classList.contains('open')){ui.journey.classList.toggle('open',open);ui.toggle.setAttribute('aria-expanded',String(open));ui.toggle.textContent=open?'Hide A1 journey':'View A1 journey'}
  function state(name){ui.status.textContent=name;ui.dot.classList.toggle('live',name==='Mia is speaking'||name==='I’m listening');ui.mic.hidden=name!=='I’m listening'}
  function wordDelay(word){const clean=word.replace(/[^A-Za-zÄÖÜäöüß]/g,''),speaking=Math.min(470,210+clean.length*17);if(/[.!?][”’"']?$/.test(word))return speaking+520;if(/[;:][”’"']?$/.test(word))return speaking+300;if(/,[”’"']?$/.test(word))return speaking+190;return speaking}
  function showSpeech(text){clearTimeout(highlightTimer);const words=text.match(/\S+/g)||[];ui.mia.replaceChildren(...words.flatMap((word,i)=>{const span=document.createElement('span');span.className='spoken-word';span.textContent=word;return i?[document.createTextNode(' '),span]:[span]}));let active=0;const advance=()=>{ui.mia.querySelectorAll('.spoken-word').forEach((word,i)=>{word.classList.toggle('active',i===active);word.classList.toggle('said',i<active)});if(active<words.length-1){const delay=wordDelay(words[active]);active++;highlightTimer=setTimeout(advance,delay)}};advance()}
  function finishHighlight(){clearTimeout(highlightTimer);ui.mia.querySelectorAll('.spoken-word').forEach(word=>{word.classList.add('said');word.classList.remove('active')})}
  function prepareWave(track){try{audioContext=audioContext||new AudioContext();const source=audioContext.createMediaStreamSource(new MediaStream([track.mediaStreamTrack]));analyser=audioContext.createAnalyser();analyser.fftSize=256;analyser.smoothingTimeConstant=.72;source.connect(analyser)}catch(error){console.warn('Waveform unavailable',error)}}
  function drawWave(){if(!analyser)return;const canvas=ui.canvas,scale=devicePixelRatio||1,width=canvas.clientWidth*scale,height=canvas.clientHeight*scale;if(canvas.width!==width||canvas.height!==height){canvas.width=width;canvas.height=height}const ctx=canvas.getContext('2d'),data=new Uint8Array(analyser.frequencyBinCount);analyser.getByteTimeDomainData(data);ctx.clearRect(0,0,width,height);ctx.strokeStyle='#10231d';ctx.lineWidth=2.5*scale;ctx.beginPath();for(let i=0;i<data.length;i++){const x=i/(data.length-1)*width,y=data[i]/255*height;i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.stroke();waveFrame=requestAnimationFrame(drawWave)}
  function startWave(){ui.wave.hidden=false;audioContext?.resume();cancelAnimationFrame(waveFrame);drawWave()}function stopWave(){cancelAnimationFrame(waveFrame);ui.wave.hidden=true}
  async function loadCurriculum(){loadLocalProgress();loadLocalWords();api=api||await ready();if(api.client){const [{data},{data:wordSkills}]=await Promise.all([api.client.from('lesson_progress').select('*').like('lesson_id','voice-tutor:A1%'),api.client.from('skill_mastery').select('*').like('skill_id','voice-vocab-a1:%')]);(data||[]).forEach(mergeProgress);(wordSkills||[]).forEach(row=>{const id=row.skill_id.split(':').pop(),current=wordProgress.get(id)||{};wordProgress.set(id,{...current,attempts:Math.max(current.attempts||0,row.attempts||0),correct:Math.max(current.correct||0,row.correct_attempts||0),learned:current.learned||Number(row.mastery)>0,lastPractisedAt:row.last_practised_at})});const legacy=progress.get('voice-tutor:A1');if(legacy?.status==='completed'&&!progress.has(lessonId(coreCurriculum[1])))mergeProgress({...legacy,lesson_id:lessonId(coreCurriculum[1])})}const resumeStep=row=>row?.status==='in_progress'?Math.max(0,(row.current_step||1)-1):0,requested=new URLSearchParams(location.search).get('lesson'),requestedIndex=curriculum.findIndex(l=>l.id===requested);if(requestedIndex>=0){const row=progress.get(lessonId(curriculum[requestedIndex]));return chooseLesson(requestedIndex,resumeStep(row))}const active=curriculum.findIndex(l=>progress.get(lessonId(l))?.status==='in_progress'),firstOpen=curriculum.findIndex(l=>progress.get(lessonId(l))?.status!=='completed'),selected=active>=0?active:firstOpen>=0?firstOpen:curriculum.length-1,row=progress.get(lessonId(curriculum[selected]));chooseLesson(selected,resumeStep(row))}
  async function credentials(){api=api||await ready();const {data}=await api.client.auth.getSession(),access=data.session?.access_token;if(!access)throw new Error('Sign-in is still preparing.');const response=await fetch(SESSION_ENDPOINT,{method:'POST',headers:{authorization:`Bearer ${access}`}}),body=await response.json();if(!response.ok)throw new Error(body.error||'Could not start a secure voice room.');return body}
  async function start(){ui.start.disabled=true;ui.start.textContent='Preparing Mia…';ui.mia.textContent='Allow microphone access when your browser asks.';state('Preparing secure voice room');try{LiveKit=LiveKit||await import('https://cdn.jsdelivr.net/npm/livekit-client@2.15.15/+esm');const c=await credentials();room=new LiveKit.Room({adaptiveStream:true,dynacast:true});bindRoom();state('Connecting to Mia');await room.connect(c.server_url,c.participant_token);await waitForAgent();state('Requesting microphone');await Promise.race([room.localParticipant.setMicrophoneEnabled(true),wait(15000).then(()=>{throw new Error('Microphone permission was not received. Allow microphone access and try again.')})]);ui.start.hidden=true;ui.pause.hidden=false;ui.fallback.hidden=true;toggleJourney(false);await present()}catch(error){console.error(error);await stop();state('Voice is unavailable');ui.mia.textContent=error.message||'The voice session could not start.';ui.fallback.hidden=false;ui.start.hidden=false;ui.start.disabled=false;ui.start.textContent='Try voice again'}}
  function bindRoom(){room.on(LiveKit.RoomEvent.ParticipantConnected,()=>{agentReady=true});room.on(LiveKit.RoomEvent.TrackSubscribed,track=>{if(track.kind===LiveKit.Track.Kind.Audio){const element=track.attach();element.autoplay=true;document.body.appendChild(element);prepareWave(track)}});room.on(LiveKit.RoomEvent.DataReceived,(payload,participant,kind,topic)=>{if(topic!==AGENT_TOPIC)return;try{handleAgent(JSON.parse(new TextDecoder().decode(payload)))}catch(error){console.warn('Unreadable agent event',error)}});room.on(LiveKit.RoomEvent.Disconnected,()=>{if(!paused&&mode!=='done')state('Connection ended')})}
  function waitForAgent(){if(room.remoteParticipants.size>0||agentReady)return Promise.resolve();return new Promise((resolve,reject)=>{const started=Date.now();publish({type:'hello'});agentTimer=setInterval(()=>{if(room.remoteParticipants.size>0||agentReady){clearInterval(agentTimer);resolve()}else if(Date.now()-started>15000){clearInterval(agentTimer);reject(new Error('Mia did not join in time. Please try again.'))}else publish({type:'hello'}).catch(()=>{})},500)})}
  function handleAgent(message){if(message.type==='ready'){agentReady=true;return}if(message.type==='agent_state'&&message.state==='listening'&&mode==='learner')state('I’m listening');if(message.type==='user_state'&&message.state==='speaking'&&mode==='learner')state('I can hear you…');if(message.type==='user_state'&&message.state==='listening'&&mode==='learner')state('Understanding…');if(message.type==='speech_started'&&pendingSpeech?.id===message.id){state('Mia is speaking');showSpeech(pendingSpeech.text);if(pendingSpeech.purpose==='completion')startWave()}if(message.type==='speech_failed'&&pendingSpeech?.id===message.id){clearTimeout(speechTimer);finishHighlight();stopWave();pendingSpeech=null;failVoice('Mia could not speak that prompt. Please retry.')}if(message.type==='speech_finished'&&pendingSpeech?.id===message.id){clearTimeout(speechTimer);finishHighlight();stopWave();const speech=pendingSpeech;pendingSpeech=null;finishSpeech(speech)}if(message.type==='transcript'&&mode==='learner'&&!processing){ui.learner.textContent=`You: ${message.text}`;evaluate(message.text)}}
  function publish(message){if(!room||room.state!==LiveKit.ConnectionState.Connected)throw new Error('Voice room is disconnected.');return room.localParticipant.publishData(new TextEncoder().encode(JSON.stringify(message)),{reliable:true,topic:LESSON_TOPIC})}
  function speak(text,purpose,stepIndex=index){const id=`${lessonIndex}-${stepIndex}-${++speechSerial}`;mode='tutor';pendingSpeech={id,purpose,stepIndex,lessonIndex,text};ui.mia.textContent=text;state('Mia is speaking');clearTimeout(speechTimer);speechTimer=setTimeout(()=>{if(pendingSpeech?.id===id){pendingSpeech=null;finishHighlight();failVoice('Mia’s audio took too long. Please retry.')}},45000);publish({type:'speak',id,text})}
  async function present(){processing=false;render();speak(steps[index].line,'prompt',index)}
  async function finishSpeech(speech){if(paused||speech.lessonIndex!==lessonIndex||speech.stepIndex!==index)return;const step=steps[index];if(speech.purpose==='completion'){let next=curriculum.findIndex((l,i)=>i>lessonIndex&&progress.get(lessonId(l))?.status!=='completed');if(next<0)next=curriculum.findIndex(l=>progress.get(lessonId(l))?.status!=='completed');if(next<0){mode='done';state('A1 journey complete');await stop(false);ui.start.hidden=false;ui.start.disabled=false;ui.start.textContent='Review this lesson';toggleJourney(true)}else{chooseLesson(next);await wait(900);await present()}return}if(speech.purpose==='success'){await advance(speech.stepIndex);return}if(speech.purpose==='retry'){beginListening();return}if(step.answers)beginListening();else{await wait(600);await advance(speech.stepIndex)}}
  function beginListening(){processing=false;mode='learner';state('I’m listening')}
  async function evaluate(text){if(processing||paused)return;processing=true;const stepIndex=index,n=normalize(text);if(n.includes('pause')||n==='stopp'||n.includes('stop')){await pause();return}if(n.includes('repeat')||n.includes('noch einmal')||n.includes('nochmal')){processing=false;await present();return}const step=steps[stepIndex];if(!step.answers){processing=false;return}state('Thinking with you');mode='thinking';const correct=step.answers.some(answer=>n.includes(normalize(answer)));await saveAttempt(text,correct,stepIndex);if(stepIndex!==index||paused)return;speak(correct?step.success:step.retry,correct?'success':'retry',stepIndex)}
  async function advance(stepIndex){if(paused||stepIndex!==index)return;if(index===steps.length-1){ui.kind.textContent='CHAPTER COMPLETE';ui.visual.textContent=curriculum[lessonIndex].title;ui.hint.textContent=curriculum[lessonIndex].goal;ui.mic.hidden=true;ui.bar.style.width='100%';await saveProgress(true);const next=curriculum[lessonIndex+1];speak(next?`Great work. ${curriculum[lessonIndex].title} is complete. Next: ${next.title}.`:'Great work. Your A1 voice journey is complete.','completion',index);return}index++;await saveProgress(false);await present()}
  async function saveAttempt(answer,correct,stepIndex){api=api||await ready();const lesson=curriculum[lessonIndex],step=steps[stepIndex],item=step.item,now=new Date().toISOString(),skillId=item?`voice-vocab-a1:${item.id}`:`voice-a1:${lesson.id}`;await api.recordAttempt({exercise_id:`voice-a1-${lesson.id}:${stepIndex+1}`,skill_id:skillId,lesson_id:lessonId(),exercise_type:'speaking',answer:{transcript:answer,transport:'livekit-deepgram',word_id:item?.id},correct,hints_used:0,response_ms:0,attempted_at:now});if(item){saveLocalWord(item,correct);const word=wordProgress.get(item.id),attempts=word.attempts,correctAttempts=word.correct;api.saveSkill({skill_id:skillId,level:'A1',domain:'vocabulary',mastery:correctAttempts/attempts,attempts,correct_attempts:correctAttempts,current_streak:correct?1:0,last_practised_at:now});const due=new Date(Date.now()+(correct?86400000:600000));api.saveReview({item_id:`vocab:A1-${lesson.unit.id}:${item.id}:speaking`,skill_id:skillId,item_type:'speaking',interval_days:correct?1:0,ease_factor:correct?2.5:2.3,repetitions:correct?1:0,lapses:correct?0:1,due_at:due.toISOString(),last_reviewed_at:now,suspended:false})}}
  async function saveProgress(done){api=api||await ready();const row={lesson_id:lessonId(),status:done?'completed':'in_progress',mastery:(index+1)/steps.length,current_step:index+1,total_steps:steps.length,last_activity_at:new Date().toISOString(),...(done?{completed_at:new Date().toISOString()}:{})};progress.set(row.lesson_id,row);saveLocalProgress(row);renderJourney();await api.saveLesson(row);await api.flush()}
  async function pause(){paused=true;pendingSpeech=null;processing=false;try{await publish({type:'interrupt'})}catch{}mode='paused';state('Lesson paused');ui.start.hidden=false;ui.start.disabled=false;ui.start.textContent='Continue voice lesson';await stop(false)}
  async function stop(reset=true){clearInterval(agentTimer);clearTimeout(highlightTimer);clearTimeout(speechTimer);stopWave();agentReady=false;if(room){await room.disconnect();room=null}if(reset)pendingSpeech=null}
  function failVoice(message){state('Voice is unavailable');ui.mia.textContent=message;ui.fallback.hidden=false;ui.start.hidden=false;ui.start.disabled=false;ui.start.textContent='Try voice again'}
  ui.start.onclick=()=>{paused=false;start()};ui.pause.onclick=pause;ui.toggle.onclick=()=>toggleJourney();ui.close.onclick=()=>toggleJourney(false);ui.tabs.onclick=e=>{const button=e.target.closest('[data-view]');if(button){journeyView=button.dataset.view;renderJourney()}};ui.list.onclick=e=>{const unit=e.target.closest('[data-unit-toggle]');if(unit){unit.setAttribute('aria-expanded',String(unit.getAttribute('aria-expanded')!=='true'));return}const button=e.target.closest('[data-lesson]');if(!button)return;if(room&&mode!=='done')return state('Pause before changing lessons');const next=Number(button.dataset.lesson),row=progress.get(lessonId(curriculum[next])),step=row?.status==='in_progress'?Math.max(0,(row.current_step||1)-1):0;chooseLesson(next,step);toggleJourney(false)};ui.send.onclick=()=>{const text=ui.typed.value.trim();if(text){evaluate(text);ui.typed.value=''}};ui.typed.onkeydown=e=>{if(e.key==='Enter')ui.send.click()};addEventListener('beforeunload',()=>stop());loadLocalProgress();loadLocalWords();render();loadCurriculum().catch(error=>console.warn('Could not load voice curriculum',error));
})();
