(() => {
  const SESSION_ENDPOINT = 'https://fallweise-voice-session.arpithpmuddi-0ee.workers.dev/api/livekit/session';
  const AGENT_TOPIC = 'fallweise.agent';
  const LESSON_TOPIC = 'fallweise.lesson';
  const steps = [
    {kind:'NOTICE',visual:'der Zug → dem Zug',hint:'The receiver or object after mit uses dative.',line:'Let’s make the dative feel natural. Der Zug means the train. After mit, der changes to dem. Listen: mit dem Zug.'},
    {kind:'YOUR TURN',visual:'with the train → mit __ Zug',hint:'der Zug → ?',line:'Now you try. How do you say, with the train?',answers:['mit dem zug'],success:'Exactly. Mit dem Zug.',retry:'Nearly. After mit, der becomes dem. Say: mit dem Zug.'},
    {kind:'TRANSFER',visual:'with the man → mit __ Mann',hint:'der Mann → ?',line:'Transfer the same pattern. How do you say, with the man?',answers:['mit dem mann'],success:'Perfect. Mit dem Mann.',retry:'Use dem for this masculine noun. Say: mit dem Mann.'},
    {kind:'NEW PATTERN',visual:'die Frau → mit der Frau',hint:'Feminine die changes to der.',line:'Now notice a different change. Die Frau becomes mit der Frau.'},
    {kind:'YOUR TURN',visual:'with the woman → mit __ Frau',hint:'die Frau → ?',line:'Your turn. How do you say, with the woman?',answers:['mit der frau'],success:'Yes. Mit der Frau.',retry:'After mit, feminine die becomes der. Say: mit der Frau.'},
    {kind:'MIXED RECALL',visual:'with the child → mit __ Kind',hint:'das Kind → ?',line:'One last pattern. How do you say, with the child?',answers:['mit dem kind'],success:'Exactly. Mit dem Kind. You now have the core dative pattern after mit.',retry:'Neuter das also changes to dem. Say: mit dem Kind.'}
  ];
  const $=id=>document.getElementById(id),ui={start:$('start'),mic:$('mic'),pause:$('pause'),status:$('status'),dot:$('liveDot'),bar:$('progressBar'),kind:$('stepKind'),visual:$('visual'),hint:$('hint'),mia:$('miaLine'),learner:$('learnerLine'),fallback:$('fallback'),typed:$('typed'),send:$('send')};
  let api,LiveKit,room,index=0,mode='idle',paused=false,processing=false,agentReady=false,pendingSpeech=null,speechSerial=0,agentTimer;
  const ready=()=>new Promise(resolve=>window.FallweiseProgress?resolve(window.FallweiseProgress):addEventListener('fallweise:ready',e=>resolve(e.detail),{once:true}));
  const normalize=s=>s.toLowerCase().normalize('NFKD').replace(/[^a-zäöüß ]/g,'').replace(/\s+/g,' ').trim();
  const wait=(ms)=>new Promise(resolve=>setTimeout(resolve,ms));
  function render(){const s=steps[index];ui.kind.textContent=s.kind;ui.visual.textContent=s.visual;ui.hint.textContent=s.hint;ui.bar.style.width=`${(index+1)/steps.length*100}%`;ui.learner.textContent=''}
  function state(name){ui.status.textContent=name;ui.dot.classList.toggle('live',name==='Mia is speaking'||name==='I’m listening');ui.mic.hidden=name!=='I’m listening'}
  async function credentials(){api=api||await ready();const {data}=await api.client.auth.getSession(),access=data.session?.access_token;if(!access)throw new Error('Sign-in is still preparing.');const response=await fetch(SESSION_ENDPOINT,{method:'POST',headers:{authorization:`Bearer ${access}`}});const body=await response.json();if(!response.ok)throw new Error(body.error||'Could not start a secure voice room.');return body}
  async function start(){ui.start.disabled=true;ui.start.textContent='Preparing Mia…';ui.mia.textContent='Allow microphone access when your browser asks.';state('Preparing secure voice room');try{LiveKit=LiveKit||await import('https://cdn.jsdelivr.net/npm/livekit-client@2.15.15/+esm');const c=await credentials();room=new LiveKit.Room({adaptiveStream:true,dynacast:true});bindRoom();state('Connecting to Mia');await room.connect(c.server_url,c.participant_token);await waitForAgent();state('Requesting microphone');await Promise.race([room.localParticipant.setMicrophoneEnabled(true),wait(15000).then(()=>{throw new Error('Microphone permission was not received. Allow microphone access and try again.')})]);ui.start.hidden=true;ui.pause.hidden=false;ui.fallback.hidden=true;await present()}catch(error){console.error(error);await stop();state('Voice is unavailable');ui.mia.textContent=error.message||'The voice session could not start.';ui.fallback.hidden=false;ui.start.hidden=false;ui.start.disabled=false;ui.start.textContent='Try voice again'}}
  function bindRoom(){room.on(LiveKit.RoomEvent.ParticipantConnected,()=>{agentReady=true});room.on(LiveKit.RoomEvent.TrackSubscribed,(track)=>{if(track.kind===LiveKit.Track.Kind.Audio){const element=track.attach();element.autoplay=true;document.body.appendChild(element)}});room.on(LiveKit.RoomEvent.DataReceived,(payload,participant,kind,topic)=>{if(topic!==AGENT_TOPIC)return;try{handleAgent(JSON.parse(new TextDecoder().decode(payload)))}catch(error){console.warn('Unreadable agent event',error)}});room.on(LiveKit.RoomEvent.Disconnected,()=>{if(!paused&&mode!=='done')state('Connection ended')})}
  function waitForAgent(){if(room.remoteParticipants.size>0||agentReady)return Promise.resolve();return new Promise((resolve,reject)=>{const started=Date.now();publish({type:'hello'});agentTimer=setInterval(()=>{if(room.remoteParticipants.size>0||agentReady){clearInterval(agentTimer);resolve()}else if(Date.now()-started>15000){clearInterval(agentTimer);reject(new Error('Mia did not join in time. Please try again.'))}else publish({type:'hello'}).catch(()=>{})},500)})}
  function handleAgent(message){if(message.type==='ready'){agentReady=true;return}if(message.type==='agent_state'&&message.state==='listening'&&mode==='learner')state('I’m listening');if(message.type==='user_state'&&message.state==='speaking'&&mode==='learner')state('I can hear you…');if(message.type==='user_state'&&message.state==='listening'&&mode==='learner')state('Understanding…');if(message.type==='speech_started'&&pendingSpeech?.id===message.id)state('Mia is speaking');if(message.type==='speech_failed'&&pendingSpeech?.id===message.id){pendingSpeech=null;failVoice('Mia could not speak that prompt. Please retry.')}if(message.type==='speech_finished'&&pendingSpeech?.id===message.id){const speech=pendingSpeech;pendingSpeech=null;if(!message.interrupted)finishSpeech(speech)}if(message.type==='transcript'&&mode==='learner'&&!processing){ui.learner.textContent=`You: ${message.text}`;evaluate(message.text)}}
  function publish(message){if(!room||room.state!==LiveKit.ConnectionState.Connected)throw new Error('Voice room is disconnected.');return room.localParticipant.publishData(new TextEncoder().encode(JSON.stringify(message)),{reliable:true,topic:LESSON_TOPIC})}
  function speak(text,purpose,stepIndex=index){const id=`${stepIndex}-${++speechSerial}`;mode='tutor';pendingSpeech={id,purpose,stepIndex};ui.mia.textContent=text;state('Mia is speaking');publish({type:'speak',id,text})}
  async function present(){processing=false;render();speak(steps[index].line,'prompt',index)}
  async function finishSpeech(speech){if(paused||speech.stepIndex!==index)return;const step=steps[index];if(speech.purpose==='success'){await advance(speech.stepIndex);return}if(speech.purpose==='retry'){beginListening();return}if(step.answers)beginListening();else{await wait(600);await advance(speech.stepIndex)}}
  function beginListening(){processing=false;mode='learner';state('I’m listening')}
  async function evaluate(text){if(processing||paused)return;processing=true;const stepIndex=index,n=normalize(text);if(n.includes('pause')||n==='stopp'||n.includes('stop')){await pause();return}if(n.includes('repeat')||n.includes('noch einmal')||n.includes('nochmal')){processing=false;await present();return}const step=steps[stepIndex];if(!step.answers){processing=false;return}state('Thinking with you');mode='thinking';const correct=step.answers.some(answer=>n.includes(answer));await saveAttempt(text,correct,stepIndex);if(stepIndex!==index||paused)return;speak(correct?step.success:step.retry,correct?'success':'retry',stepIndex)}
  async function advance(stepIndex){if(paused||stepIndex!==index)return;if(index===steps.length-1){mode='done';state('Lesson complete');ui.kind.textContent='A SMALL WIN';ui.visual.textContent='mit dem · mit der';ui.hint.textContent='You retrieved the dative pattern aloud.';ui.mia.textContent='Great work. Your progress is saved.';ui.mic.hidden=true;ui.bar.style.width='100%';await saveProgress(true);await stop(false);return}index++;await saveProgress(false);await present()}
  async function saveAttempt(answer,correct,stepIndex){api=api||await ready();await api.recordAttempt({exercise_id:`voice-a1-dative:${stepIndex+1}`,skill_id:'voice-a1:dative-mit',lesson_id:'voice-tutor:A1',exercise_type:'voice',answer:{transcript:answer,transport:'livekit-deepgram'},correct,hints_used:0,response_ms:0,attempted_at:new Date().toISOString()})}
  async function saveProgress(done){api=api||await ready();await api.saveLesson({lesson_id:'voice-tutor:A1',status:done?'completed':'in_progress',mastery:(index+1)/steps.length,current_step:index+1,total_steps:steps.length,last_activity_at:new Date().toISOString(),...(done?{completed_at:new Date().toISOString()}:{})});await api.flush()}
  async function pause(){paused=true;pendingSpeech=null;processing=false;try{await publish({type:'interrupt'})}catch{}mode='paused';state('Lesson paused');ui.start.hidden=false;ui.start.disabled=false;ui.start.textContent='Continue voice lesson';await stop(false)}
  async function stop(reset=true){clearInterval(agentTimer);agentReady=false;if(room){await room.disconnect();room=null}if(reset)pendingSpeech=null}
  function failVoice(message){state('Voice is unavailable');ui.mia.textContent=message;ui.fallback.hidden=false;ui.start.hidden=false;ui.start.disabled=false;ui.start.textContent='Try voice again'}
  ui.start.onclick=()=>{paused=false;start()};ui.pause.onclick=pause;ui.send.onclick=()=>{const text=ui.typed.value.trim();if(text){evaluate(text);ui.typed.value=''}};ui.typed.onkeydown=e=>{if(e.key==='Enter')ui.send.click()};addEventListener('beforeunload',()=>stop());render();
})();
